### ISSUE TITLE
Мерцание ATListBox во время прокрутки

### ISSUE THREAD

**Issue by eastorwest** [Alexey-T/ATButtons#1]
Обнаружил мерцание ATListBox во время прокрутки... и простое решение - в конструкторе TATListbox.Create добавить строчку DoubleBuffered := true; в конце.

**Comment by Alexey-T** [comment]
хм, в Cudatext- не вижу мерцания (диалог F1). win xp sp3. как увидеть?

**Comment by eastorwest** [comment]
Проверяю также на WinXP SP3 в CudaText (1.2.10) в диалоге списка команд (вызывается по F1), а также в области Output после вывода многострочного файла (300+ строк) через ExtTool. При любой попытке прокрутить: либо мышью тянуть ползунок, либо нажимать на кнопки вверх/вниз наблюдаю как будто перерисовку фона и последующее восстановление изображения текста в этих компонентах. Возможно железо послабее, что заметно становится.
После исправления (DoubleBuffered := true) и пересборки CudaText все стало нормально. Возможно, что особенность Lazarus и его потомков от TCustomControl, потому что применяю этот путь исправления не впервые.
Нашел рекомендацию в Lazarus-wiki по ссылке http://wiki.lazarus.freepascal.org/Developing_with_Graphics#Create_a_custom_control_which_draws_itself 
""MyDrawingControl.DoubleBuffered := True;" is required to avoid flickering on Windows. It has no effect on gtk. "

**Comment by Alexey-T** [comment]
Вы меня убедили видимо...

**Comment by Alexey-T** [comment]
done.

**Comment by eastorwest** [comment]
Благодарю!)
