### ISSUE TITLE
RadialPie dont work in Delphi version

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATButtons#11]
ATgauge

        {$ifdef FPC}
        C.RadialPie(r2.Left, r2.Top, r2.Right, r2.Bottom,
          16*90, //starting angle: 90 deg
          -Round(16*Alfa) //pie angle: -Alfa deg
         );
        {$endif}

**Comment by Alexey-T** [comment]
@srd-software 
you must use TCanvas.Pie with adjusted params.
RadialPie params are:

ellipseX1, ellipseY1, ellipseX2, ellipseY2,
start_angle_in_16th_of_degrees,
end_angle_in_16th

**Comment by Alexey-T** [comment]
avoided RadialPie. @srd-software Pls test?

**Comment by srd-software** [comment]
Yes, that worked! I hunted for stuff and worked on it all afternoon and this evening and I finally got it working too. Here's what I came up with:
```
        if Alfa > 0 then
        begin
          StartAngle:= 90;
          FinishAngle:= StartAngle + Round(Alfa);
          CenterWidth := (r2.Width div 2);
          CenterHeight := (r2.Height div 2);

          C.Pie(r2.Left, r2.Top, r2.Right, r2.Bottom,
            CenterWidth +round(CenterWidth*cos(StartAngle*pi/180)),
            CenterHeight -round(CenterHeight*sin(StartAngle*pi/180)),
            CenterWidth +round(CenterWidth*cos(FinishAngle*pi/180)),
            CenterHeight -round(CenterHeight*sin(FinishAngle*pi/180))
           );
        end;
```
It works great! However, mine "spun" in the opposite direction of yours. It worked fine but it wouldn't have matched your lazarus as closely. Well, at least I learned stuff!
