### ISSUE TITLE
Delphi publishing

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATButtons#13]
Stan, could you publish it in Delphi package manager (getit?)
@srd-software

**Comment by Alexey-T** [comment]
http://docwiki.embarcadero.com/RADStudio/Rio/en/GetIt_Package_Manager

**Comment by Alexey-T** [comment]
And ATTabs

**Comment by srd-software** [comment]
I'll try. I've never done that before so let me look at it and of course, if I can do that I will.

**Comment by srd-software** [comment]
I'm not finding anything on how to submit a library to getit. Do you have any links or info??

**Comment by srd-software** [comment]
BTW, if you can, I highly recommend installing the bookmarks and navigator plugins from getit. They used to be part of Parnassus but embarcadero bought them. But they are worth having.

**Comment by Alexey-T** [comment]
Guess you need to open Getit dialog, login there, then you ll have Submit available

**Comment by srd-software** [comment]
No, all that has is stuff to get. I joined a forum that has a lot of stuff on getit and asked about it there. Hopefully I'll hear back soon. As soon as I do I'll see what I can do about getting the components up there.

https://community.idera.com/developer-tools/general-development/f/getit-and-third-party/69303/how-do-you-submit-a-component-to-getit-i-can-t-seem-to-find-any-info-on-that-anywhere

**Comment by srd-software** [comment]
Alexey, 

Finally got an answer on the forum. It's apparently real hard to get things submitted which makes no sense! However, I'll put the only link that seems to be working below. It's an online form to fill out. I can try to fill it out but I think you'd be better for that as it's asking for vendor info, version and library info. Some of that I'd have to guess at. Take a look. If you want me to fill it out that's OK too, just let me know.

https://docs.google.com/forms/d/e/1FAIpQLScd8j3NHgHne0wUzm3Q6fKdYf-XpPq4oH5TJ5ZebSC6iqZ0iw/viewform

**Comment by Alexey-T** [comment]
Stan, i looked at this doc.
ATFlatControls

email: Stan's email
name: Stan's name
ver: 2019.06.23
desc: Several custom-drawn controls, used in CudaText
homepage: https://github.com/Alexey-T/ATFlatControls
tags: listbox scrollbar progressbar gauge flat
categ: Components
vendor: UVviewsoft.com
vendor url: http://uvviewsoft.com/
vendor contact: https://github.com/Alexey-T/ATFlatControls/issues
lic: MPL 2.0

Better you submit it and support later that Getit entry, pls

**Comment by srd-software** [comment]
I submitted both the flat controls and tabs. I'll let you know if I hear anything from them.

**Comment by srd-software** [comment]
Alexey,

Got the following in an email this morning:

> Serge Pilko <serge.pilko@embarcadero.com>
> Fri 6/28/2019 4:02 AM
> Hello,
> 
> We are adding ATFlatControls package to the GetIt. Can you provide a little bit more expanded description for GetIt listing? Maybe explain what does it mean CudaText, etc.
> 
> Best regards, Serge Pilko.

Do you want me to respond? If so I'll need the info requested from you to pass on to them.

Stan

**Comment by Alexey-T** [comment]
Info could be:

Set of several custom-drawn controls, independant from OS: Button, Toolbar, Listbox, ScrollBar, StatusBar, Gauge. They are used/tested in cross-platform text editor CudaText. Supports VCL only.

**Comment by Alexey-T** [comment]
yes, pls respond. Need longer text?

**Comment by srd-software** [comment]
I sent him what you wrote me above. If that's not enough I'll let you know. Thanks

**Comment by srd-software** [comment]
ATFlatControls and ATTabs are deployed now on getit:

> Serge Pilko <serge.pilko@embarcadero.com>
> Mon 7/1/2019 4:43 AM
> Hello,
> 
> We have deployed ATFlatControls and ATTabs to the GetIt. Please, check from your end.
> 
> Best regards, Serge Pilko.

![ATFlatControls on GetIt](https://user-images.githubusercontent.com/51385541/60434444-601e3b00-9bc4-11e9-85c0-c6d1933ee927.png)
![ATTabs on GetIt](https://user-images.githubusercontent.com/51385541/60434445-601e3b00-9bc4-11e9-96d3-d1f87cc81b76.png)

**Comment by Alexey-T** [comment]
Great news. I am glad. thanks!
