### ISSUE TITLE
Review TMemo Demo

### ISSUE THREAD

**Issue by srd-software** [Alexey-T/ATButtons#18]
Alexey, when time permits, I have a demo for a TMemo using the ATscrollbar. It will show how to:

- Use a custom ATscrollbar with a TMemo
- Change Font (size, style, allows both proportional and monospaced tests)
- Change WordWrap
- How to scroll the memo from the custom ATscrollbar
- How to scroll the ATscrollbar from the memo
- Turn both system and custom scrollbars on at the same time for comparison
- Simple color theme (regular and dark)
- File drop to TMemo
- WheelScroll TMemo and ATScrollbar

![Image36](https://user-images.githubusercontent.com/51385541/60542814-0b68e600-9cd2-11e9-8718-3a86b38e5c65.png)

I think the vertical stuff is OK (memo controls sb; sb controls memo), and the horizontal seems OK (sb controls memo). But you might check what I've done for horizontal memo controls sb. There's not really a good way that I can find to get the memo _horizontal_ scroll info over to the sb but I did the best I could.

I think this demo will be very useful as there are a lot of links when searching for this kind of thing but very little that helps much. Searches such as: scroll tmemo, tmemo custom scrollbar, how to scroll tmemo when its scrollbars are hidden, etc.

Like I say, I need something like this for reference anyway so if you decide not to use it that's OK.

**Comment by Alexey-T** [comment]
It is Ok - I cannot review it coz I have notebook without Delphi on vacation . Go on, make pull req...

**Comment by srd-software** [comment]
I put it up. Don't worry about it until you get back!
