### ISSUE TITLE
DirectJumpOnClick

### ISSUE THREAD

**Issue by srd-software** [Alexey-T/ATButtons#22]
Alexey,

I'm having trouble with the atscrollbar DirectJumpOnClick. If true, it works if I click in the PageUp rect. But if I click in the PageDown rect the scroll always jumps to the bottom (in a vertical SB; or all the way to the right in a horizontal SB). Assuming PageUp and PageDown should work in a similar way, the problem seems to be in the code below. I played with it a little but I'm not good with the relational math stuff like you are so I was not able to get it to work.
```
      if FTheme^.DirectJumpOnClickPageUpDown then
      begin
        Position:= Math.Min(FMax-FPageSize,
                   Math.Max(FMin,
                   CoordToPos(X, Y)));
      end
```
![ss3](https://user-images.githubusercontent.com/51385541/60768736-d28b9100-a084-11e9-8b38-4a814b83ea4c.gif)

Thanks Alexey!

**Comment by Alexey-T** [comment]
hmmm. GIF shows that you clicked below - then code uses your click y as vertical edge of thumb- and vertical thumb goes to that clicked y. so no bug.

**Comment by Alexey-T** [comment]
I want to say- test on big height of scrollbar and you ll see that its OK now.

**Comment by srd-software** [comment]
I tried it with 48 items in the virtualstringtree, and then DirectJumpOnClick does appear to work. So I suppose I just didn't have enough items in the tree to make it work correctly. OK, I can see that.

That brings up a related question I have. The LineSize property is (I think) equivalent to SmallChange in the windows scrollbar API. You might think about renaming LineSize to SmallChange. Leaving it as is is OK too, might break too much existing code to change that name now.

However, regardless of changing LineSize naming or not, I would suggest adding a LargeChange property (or var) to make the atscrollbar similar to the existing win scrollbar API. LargeChange is commonly set to SmallChange * 3 in code. So if LargeChange were > 0 and DirectJumpOnClick was false, LargeChange would set the PageUp and PageDown position directly in mousedown like the win scrollbar API (i.e., DoScrollBy(±FLargeChange)). If LargeChange were 0 then the code as it is now would run the same way as before (either DirectJumpOnClick or DoScrollBy(±FPageSize)).

I could do a LargeChange prop) and then upload it so you could try it and see what you think about that.

**Comment by Alexey-T** [comment]
I’m not sure Win api has such a thing- are you sure? Why page size not ok?

**Comment by Alexey-T** [comment]
And you can set PageSize to 3, isn’t it ok?

**Comment by srd-software** [comment]
Yes, you are correct, it's not a win API thing as such, more of a convention of win scrollbar components. Here's a dotnet link: https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.scrollbar.largechange?view=netframework-4.8

I tried PageSize to 3 and it throws the thumb size off. 

However, I think you may be right, this may not really be needed. It's a convention of many scrollbar components but not strictly speaking a required thing. I'll put in a screenshot of it working so you can see what I'm referring to (the delphi IDE is a good example (arrow clicks move small, track clicks move by 3 or so):

![ss3](https://user-images.githubusercontent.com/51385541/60773830-967a1f80-a0c8-11e9-9ac6-75300751c119.gif)

**Comment by srd-software** [comment]
After thinking on this, I think I'll just use DirectJumpOnClick for now and see how that works. If I decide I really need a LargeChange kind of thing that's super easy for me to add in to my own copy of the component later on.

**Comment by Alexey-T** [comment]
It’s ok to add LargeChange- if such a thing is used in some popular app ..

**Comment by srd-software** [comment]
I added LargeChange: #23 
Theme setting of DirectJumpOnClick still overrides "manual" settings of FPageSize and FLargeChange. If FLargeChange is 0 (the default) it all works exactly as before, so should break no existing code. If you set the DirectJumpOnClick to false and FLargeChange to something > 0 (in this case 3) you will now get this behavior:

![ss3](https://user-images.githubusercontent.com/51385541/60807404-d7167f00-a142-11e9-9201-b572de43804a.gif)

Scroll jumps by 3 when track area clicked, and by 1 when arrows clicked. I tried this with the other settings (DirectJumpOnClick and FLargeChange = 0) and on a horizontal SB it all looks OK. Note: darker gray SB is an ALscrollbar, just disregard it. It's still in there for testing.

**Comment by Alexey-T** [comment]
It is okay, thanks. You can also rename LineSize to SmallChange

**Comment by srd-software** [comment]
OK, that's done: #24

**Comment by CudaText-addons** [comment]
ops, I just did it by myself. So close it.

**Comment by Alexey-T** [comment]
i already did it by myself. So i close it.
