### ISSUE TITLE
Suggestions for scrollbar

### ISSUE THREAD

**Issue by srd-software** [Alexey-T/ATButtons#27]
Hi Alexey,

I am still working with the scrollbar stuff. I have a couple of suggestions for when you have time to review. 

One is Decor3D. I'll add an animated gif to demo below but the idea is to give the thumb grippys a 3D look when desired. Mostly just a visual enhancement, but this can also be of help if they are changing color schemes on the fly as they might "lose" the grippys depending on the color used. If they are "3D" then the app doesn't have to "worry" as much about the color settings. 

Second, I added a ThumbMarkerDecorSpace to the SB theme. It lets the user put more space between the grippy lines.

Here's a demo that I hope explains these items. NOTE: Please **_CLICK_** on the gif below to see it in correct resolution (it looks bad in the github browser image below!) Normally this is not an issue but I want you to see it as it really looks...

![ss3](https://user-images.githubusercontent.com/51385541/60833391-68094c80-a17b-11e9-95cf-6895e08fb470.gif)

**Comment by Alexey-T** [comment]
nnnDecorSpace - Ok, agree.
Decor3D - Ok, agree. With additional themed color for light lines.

**Comment by srd-software** [comment]
Yes, I was thinking the same thing on the light lines. I'll do that stuff soon and let you know.

**Comment by srd-software** [comment]
Hopefully this will do it: #28 

Feel free to rename anything if needed.

**Comment by Alexey-T** [comment]
submitted the 'review'.

**Comment by srd-software** [comment]
Let me know if you want a new pull request! Not sure if all these fixes will make it OK. Just let me know.

**Comment by Alexey-T** [comment]
Stan- I've renamed some new theme-props. Pls adapt your code.

**Comment by Alexey-T** [comment]
And-- added theme prop ColorThumbDecor (now we have two decor colors)

**Comment by srd-software** [comment]
OK, very nice. I've been playing with several test apps this morning and it all works really well and looks good.

**Comment by srd-software** [comment]
I added a Decor Double checkbox to the Delphi demo and made a pull request. I also updated the lazarus version but when I uploaded that one there were more changes showing than there should have been, I think due to my version of lazarus being slightly older than yours, so I didn't want to muddy things up with that yet.

**Comment by Alexey-T** [comment]
Reason- If Lazarus saves form on Win, it makes all controls shifted a little, from Lin version

**Comment by srd-software** [comment]
Yeah, that's what it did. Plus the lazarus version number is different too. Do you want me to try uploading that again?

**Comment by Alexey-T** [comment]
Nope, demo is ok
