### ISSUE TITLE
Atlistbox question

### ISSUE THREAD

**Issue by srd-software** [Alexey-T/ATButtons#32]
Hi Alexey,

Couple of things on the atlistbox. I have one set up as ownerdraw with VirtualMode = false and enough items to activate a scrollbar. The problem I'm having is if I turn HotTrack on, I get a lot of flicker in the built-in scrollbar when mousing over the items (if you move over them slowly it looks OK, but if the mouse is moving medium to fast speed you see it). The only thing I've found that helps (but doesn't seem to eliminate it entirely) is in MouseMove by changing Invalidate to Refresh:
```
    if FHotTrackIndex<>NewIndex then
    begin
      FHotTrackIndex:= NewIndex;
      Refresh; //helps but can still get a little flickering
      //Invalidate;
    end;
```
I doubt that's the real answer. Might be something in the erase background message but I can't figure it out.

Second issue is if I set my atlistbox1.scrollbar.width from my app's code (i.e., in form create), the width doesn't change. I have to put the width change into something like my app's idle or listbox drawitem code to get it to change. Note that I've commented this out while testing the flicker problem above, so this is not the problem on that issue).

I can always replace the built-in scrollbar with an external one, or turn off HotTrack but those options defeat useful things about using the listbox as intended!

Any ideas welcomed. 

Stan

**Comment by Alexey-T** [comment]
Pls move question-2 to new topic.
Flickering: we have overriden Invalidate
```
procedure TATListbox.Invalidate;
begin
  if Assigned(FScrollbar) then
    FScrollbar.Update;

  inherited Invalidate;
end;
```
what if you add "if assigned(FScrollbar) and FScrollbar.Visible"?

**Comment by Alexey-T** [comment]
Idea-2. Toggle the DoubleBuffered prop.

**Comment by Alexey-T** [comment]
Q-2. The reason is
```
procedure TATScrollbar.Update;
begin
  if IsHorz then
    Height:= DoScale(FTheme^.InitialSize)
  else
    Width:= DoScale(FTheme^.InitialSize);

  Invalidate;
end;
```
so you need to change Theme's prop.

**Comment by srd-software** [comment]
Tried both of those and no luck. 

All I've gotten to work so far is to set the atlistbox.scrollbar.width := 0 and then use an external atscrollbar instead.

**Comment by srd-software** [comment]
> Q-2. The reason is
> 
> ```
> procedure TATScrollbar.Update;
> begin
>   if IsHorz then
>     Height:= DoScale(FTheme^.InitialSize)
>   else
>     Width:= DoScale(FTheme^.InitialSize);
> 
>   Invalidate;
> end;
> ```
> 
> so you need to change Theme's prop.

If I do that, won't all the atscrollbars in the app use the new setting? I was wanting to have a narrow bar in my list and all the others are OK at default. 

Looks like maybe the external SB is the way for me to go with this particular problem.

**Comment by Alexey-T** [comment]
About q-2, see above

**Comment by Alexey-T** [comment]
So you must change Theme of those bar which is deferent from other bars. Set theme colors the same and InitialSize not the same

**Comment by srd-software** [comment]
> So you must change Theme of those bar which is deferent from other bars. Set theme colors the same and InitialSize not the same

Ah, that worked, thanks. I was wondering what InitialSize was for.

**Comment by srd-software** [comment]
As far as the flicker problem, for now I'll use the external SB but I'll keep looking at the listbox code and see if I can figure anything out.

**Comment by Alexey-T** [comment]
All right

**Comment by Alexey-T** [comment]
Stan, problem is not visible on Win10 (and Lin) in Lazarus. so maybe Delphi dependant.

**Comment by srd-software** [comment]
OK. I'll look at the erase bgnd message too. Seems to be an issue sometimes.

**Comment by srd-software** [comment]
Alexey, 

I think I've found the fix for the fscrollbar flicker problem in MouseMove:
```
      FHotTrackIndex:= NewIndex;
      if Assigned(FScrollbar) and FScrollbar.Visible then
      begin
        r := ClientRect;
        r.Right := ClientWidth;
        {$ifdef FPC}
        InvalidateRect(Handle,@r,false);
        {$endif}
        {$ifndef FPC}
        InvalidateRect(Handle,r,false);
        {$endif}
      end
      else
        Invalidate;
```
From what I could find online, Invalidate repaints the entire control. So by eliminating the rect the fscrollbar is on and refreshing only the area needed, it fixes the fscrollbar flicker. Since this only happens in mousemove with hottrack enabled, I don't think there's any bad effects from not using the overridden Invalidate. I don't think we need to update the fscrollbar here since mousemove is not changing its position or parameters.

I tried this in lazarus and had to add the slight diff on InvalidateRect. It seems to work just fine in the demo but I'm not a lazarus expert like you so maybe you can review and verify that it looks OK.

**Comment by Alexey-T** [comment]
applied that fix, thanks - pls check it.

**Comment by srd-software** [comment]
Yes, looks good. Thanks for the better code too! That one was a _real_ difficult one to find.

I still get a little of the funny business in the SB when resizing the control at run time with a splitter, but that's not as noticeable. I'll look into that as well but it was the mouseover that was really noticeable.

**Comment by Alexey-T** [comment]
Allright.

**Comment by srd-software** [comment]
Still looking at resizing but while doing that I found I needed the new invalidate code for mouseenter/leave. So I added those and moved the invalidaterect code to its own proc. #33

**Comment by Alexey-T** [comment]
Ok, thanks.

**Comment by srd-software** [comment]
I have a fix for the resize problem. Took awhile to get github to work, it's apparently having issues today!

#34

**Comment by srd-software** [comment]
A little more fine tuning. This update keeps the fscrollbar from disappearing in some cases. #36
