### ISSUE TITLE
Feature request: ATListbox: expose OnOwnerDraw scrollbars

### ISSUE THREAD

**Issue by aducom** [Alexey-T/ATButtons#37]
The ATScrollbar allows painting the canvas which is great if you want to make a dark-theme. The sample shows how to do this. Although I don't like the use of characters like ^v<> it appears to work quite well. However the ATScrollbar is also used in the ATListbox, which is great. However the onownerdraw of the scrollbar is not exposed. There are virtually two scrollbars involved (horizontal and vertical) but actually I think that exposing one event onOwnerDrawScrollBar that points to the FScrollbar. I don't mind looking into this if you think this is a good idea, because there are other options, like adding the event by code, or perhaps the theming options in the component. To be honest I couldn't figure out how this supposed to work as I think it has to do with OS theming, but under Lazarus I couldn't get the manifest idea to work well. Other option could be a separate component to allow theming, and actually I think that might be a better way. What do you think?

**Comment by Alexey-T** [comment]
Will try to add owner draw event of bar to listbox, or maybe expose the scrollbar object.

**Comment by aducom** [comment]
Both options work well. For consistency I would suggest only to expose the ownerdraw and have that handling both scrollbars. Not sure, if the horizontal scrollbar is a ATScrollbar, but if it isn't I am suggesting it. I think you have a very nice set that allows light/dark theming of Lazarus/Delphi that works quite well. Good work!

**Comment by Alexey-T** [comment]
Listbox don’t have the h bar!
Just added event OnDrawScrollbar, check it

**Comment by aducom** [comment]
Will do! thnx.
