### ISSUE TITLE
TATabs generates ontabclick event before initialization of TForm

### ISSUE THREAD

**Issue by aducom** [Alexey-T/ATButtons#42]
I'm not sure if this is intentional or a bug. In Lazarus all components are created and then the TForm OnCreate get's fired. In the TForm OnCreate and/or OnShow custom components are useually being created and initialized. 
If you change a tab and bind this to an event then you might need to (re)initialize things. That brings issues as the ontabclick event is triggered even before the TForm OnCreate. So you cannot access custom created variables that will be created in the tform.oncreate like tlists, tstringlists etc.
Of course, there are always ways to solve issues, but I thought I should mention this.

**Comment by Alexey-T** [comment]
it is valid comment. i suggest to add "if not csLoading in ComponentState" or smth. can you try to add it?

**Comment by aducom** [comment]
I assume that you mean to add it to your component code? Will try. Been ages I've been working creating components and never done it for Lazarus, but I'll try.

**Comment by Alexey-T** [comment]
Yes, to my code

**Comment by aducom** [comment]
I am working on it, but ended up in a stack error. Reverted back to the original, but problem persists on attabs.pas:1137 
Will look into this further some other moment, I fear that I have to reinstall Laz.

**Comment by Alexey-T** [comment]
I guess it’s ok to add this /If/ above the call of FOnTabChange

**Comment by aducom** [comment]
I fixed it. Code below
```
   procedure TATTabs.SetTabIndex(AIndex: integer);
   //note: check "if AIndex=FTabIndex" must not be here, must be in outer funcs.
   //Sometimes SetTabIndex(TabIndex) is needed, eg in DeleteTab().
   var
     CanChange: boolean;
     doClickEvent : boolean;
   begin
     doClickEvent :=  (aIndex <> FTabIndex);      // Only generate onClickEvent when the tab changes
                                                  // This prevents a potential endless loop if the event
                                                  // is triggered in software (aducom)
     if csLoading in ComponentState then
       FTabIndexLoaded:= AIndex;

     if IsIndexOk(AIndex) then
     begin
       CanChange:= true;
       if Assigned(FOnTabChangeQuery) then
       begin
         FOnTabChangeQuery(Self, AIndex, CanChange);
         if not CanChange then Exit;
       end;

       FTabIndex:= AIndex;

       MakeVisible(AIndex);
       Invalidate;
       if Assigned(FOnTabClick) then
          if not(csLoading in ComponentState) then    // avoid click event while component is being created (aducom)
             if doClickEvent then
                FOnTabClick(Self);
     end;
   end; 
```

**Comment by Alexey-T** [comment]
Use these fence chars, pls. edited the post.

    ```

**Comment by Alexey-T** [comment]
Pls see my comment in code
   //note: check "if AIndex=FTabIndex" must not be here, must be in outer funcs.
   //Sometimes SetTabIndex(TabIndex) is needed, eg in DeleteTab().

**Comment by aducom** [comment]
I know, but this only influences the onclick. You will get infinite loops as I had one if you don't, If you think that it should trigger on deleting tab I can modify it further.
It is not logical to trigger if a tab is being deleted. Orignal flow is not influenced.

Let me explain it a bit better. If you change a tab then the event is triggered. If this trigger is caused by some program code it will trigger also. It makes no sence to trigger if the tab is not being changed. Of course you can do that from the outside, but if you don't (and it's not so obvious to do) then you end up with a stack error and that will be hard to find. I think you should do it in the component. If you delete a tab, then it is not logical to trigger an onclick because the deleted tab is not present any more.

**Comment by Alexey-T** [comment]
okay. made this change, pls check it.

**Comment by aducom** [comment]
Confirmed. Thnx.

**Comment by Alexey-T** [comment]
partially reverted, sorry- it gave problems in CudaText- initial tab was not shown+ clicking tab title didn't focus the tab.

**Comment by aducom** [comment]
I'm back to my stack error. Well, for now, I'll work with my own patch. Am not using Cudatext so can't judge implications. But it's good that the initialization issue if fixed. I don't have issues showing the initial tab. Focus issue is an interesting one though. (FTabIndex=-1 in the constructor will trigger initial change)

**Comment by aducom** [comment]
What do you think of adding an event ontabchanged? That will only fire if oldtab != newtab, made an implementation that I will test next week. Same for property tabvisible (ttabsheet compatibility)

**Comment by Alexey-T** [comment]
Maybe show ur implementation, is it small code

**Comment by aducom** [comment]
Well, the onchange is a few lines of code and works well. The tabvisible should be similar, but I'm still strugling with the application flow, no matter what value I give the property, the status is always false. But I'll get to it.

**Comment by aducom** [comment]
Ok, I have added the ontabchanged event and tested it. Should work ok with your other components. I also added the tabvisible property and two routines ShowTab(index) and HideTab(index). The function takes care of the tabindex to avoid issues with bound notebookpages if any. The issue is that I don't want to publish the full text here, unless you want me to. I have a small sample too showing the features. I can make a downloadable zip and publish for you. Let me know.

**Comment by Alexey-T** [comment]
you can make a pull-request on github. in ATFlatCon repo, find file attabs.pas on site, then press EDIT button to edit it, paste your file.

check the changes in pull-req page.

**Comment by Alexey-T** [comment]
Thanks, I have fixed your code a little.

**Comment by aducom** [comment]
> 
> 
> Thanks, I have fixed your code a little.

Yes, seen that, but logical choice ;-)
