### ISSUE TITLE
Sublime way to paint tabs

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATButtons#45]
@srd-software I want to get prototype of painting tabs like Sublime Text (ST) does. pls download it. open file 'Theme - Default.sublime-package'. (On Linux: /opt/sublime_text/Packages).
see PNG pics inside this ZIP file:
```
tab@3x.png
tab_highlight@3x.png
tab_shadow@3x.png
light/tab_border@3x.png
```
- mask for entire tab
- mask for top edge (maybe for user colored tabs?)
- shadow
- border above tab

now we need the prototype which takes _similar_ png's and paints nice tab using them. tab must be colored with any user-defined color. (problem: I dunno how to mix the colored rectangle + mask, I dunno how ST makes nice gray borders).

for me, it is the better way than our themes.

**Comment by srd-software** [comment]
Alexey, I put a test project together in delphi. It's in a repository called png overlay test. It's not a prototype but it may give you some ideas for this.

**Comment by Alexey-T** [comment]
Maybe will look in the next days... tks

**Comment by Alexey-T** [comment]
I saw it, nice helper functions, but the shadow is not painted below the tab (Delphi 10.3), and not sure I can do this in Laz png code

**Comment by srd-software** [comment]
Maybe check out Graphics32 in sourceforge? Looks like it may have what you need and is both delphi and lazarus...
