### ISSUE TITLE
ScrollStyleHorz, ScrollStyleVert instead of one ScrollBars

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATButtons#46]
@srd-software Made this change, in git. it is more logical to have 2 props for 2 bars than to have one prop for both. 2 props have 3*3 combinations, and old one had 7 combinations.

**Comment by srd-software** [comment]
Yes, even better. Works OK here.

Right now I'm just using ellipses in my app's listbox item text. I plan to add a toggle between item text ellipses or full item text with horz scrollbar when I have some time to try the horz SB as well.
