### ISSUE TITLE
New version is now in getit

### ISSUE THREAD

**Issue by srd-software** [Alexey-T/ATButtons#47]
Alexey, they have deployed new version and disabled ATTabs package.

**Comment by Alexey-T** [comment]
Good, thank you!

**Comment by Alexey-T** [comment]
@srd-software We have lot of changes since 2019, please can you update the code in Getit?
(after test that all compiles in Delphi)

**Comment by srd-software** [comment]
Hi Alexy,

Below is the info I sent them before. Look it over and make any changes and I'll submit it with the new info. I used my email address last time and I can do that again if you'd like.

The text fields you should be able to type into if there are changes. The checkbox and radiobox stuff will show you what we did before, but they don't seem to respond. So, for changes to those, just type in what you want right below the set of check or radio boxes. See the Category boxes for an example.

If this doesn't work let me know. Otherwise I'll take your changes, copy and paste them into the current form and resubmit the newer stuff.

Stan
Embarcadero GetIt Submission Information
Use this form to provide information to Embarcadero Technologies to include packages, components and libraries in the GetIt catalog.

A note about Trial versions:
For trials of full products we prefer the limited functionality trial that provides some sort of utility to users even if they don't upgrade to the full version.

There is currently no eCommerce component. Your component would need to include the mechanism to send users to your shopping cart to obtain the full license.

If you offer multiple editions of your product, with each higher tier offering more functionality, only offer one trial of the top tier. Then when customers go to purchase offer them a breakdown of which features are in which version and let them choose then. There is not enough information in GetIt for users to choose which tier they want, and if you let everyone try the best features then they are more likely to buy them.

Email address *
***@***.***
[Captionless Image]

Introduction
If you have any questions about the process you can follow up with Jim McKeeth via ***@***.******@***.***> or on Skype as jimmckeeth. The final decision to include or exclude anything in GetIt is made by Embarcadero Technologies. We are looking for libraries that bring value to developers using our tools, doesn't conflict or circumvent the the higher end SKUs (adding Client Server technology to Professional), has acceptable licenses and targets the latest versions of RAD Studio. Also, please make sure you are a product manager or owner for anything you are submitting. For open source projects please get the primary project manager involved. There is a comments question at the end where you can explain your relationship to the project if it is complicated. You can read more information at http://community.embarcadero.com/index.php/article/news/16027-submitting-libraries-to-getit<https://www.google.com/url?q=http://community.embarcadero.com/index.php/article/news/16027-submitting-libraries-to-getit&sa=D&ust=1561295396373000&usg=AFQjCNGRPZwFHEP0SQGDrH2E1u1tpb3baA>

About You
Please make sure you are a product manager or owner for anything you are submitting. For open source projects please get the primary project manager involved. There is a comments question at the end where you can explain your relationship to the project if it is complicated.

Your Name *
Stan R Day

About the Project
This is how it will appear in GetIt

Project name *
Name of the catalog item (short title)
ATTabs

Version *
Version of the catalog item
2019.06.18

Description *
Description of the catalog item for publishing in the GetIt catalog (consider space is fairly limited)
Delphi/Lazarus component for lite tabs. OS independent, fully custom drawn.

Link to image *
PNG Image to be displayed in the GetIt window. Image should be square. Recommended size is 154x154.
https://avatars0.githubusercontent.com/u/4154978?s=460&v=4

Project Homepage *
Homepage (URL) of the project or library
https://github.com/Alexey-T/ATTabs

Tags *
Comma separated list of keywords to help the user find this entry on the catalog
Tabs

Category *

  *    Libraries
  *    Components
  *    Internet of Things
  *    Trial
  *    Connectors
  *    Industry Template
  *    IDE Plugins
  *    Styles
  *    Sample Projects
  *    Tool or Utility
  *    Other:

TYPE IN CHANGES HERE!...
About the Company or Team
If users want more information about the company or team behind this library

Vendor name *
Name of the vendor for the catalog item; for open source libraries can be name of project or team behind it
UVviewsoft.com

Vendor URL *
URL of the vendor for the catalog item (or of the open source project/team)
http://uvviewsoft.com/

Vendor Contact *
Contact URL or email to contact vendor
https://github.com/Alexey-T/ATFlatControls/issues

Entry details
This is the nitty gritty that is used during the installation process

Library License Name *
e.g. Mozilla Public License 1.1 (MPL 1.1), commercial, trial, etc.
MPL 2.0 and LGPL

Library License File or EULA URL *
URL to the plain text representation of the full license file
https://github.com/Alexey-T/ATFlatControls/blob/master/license.txt

License Type *

  *    Time limited Trial
  *    Limited functionality Trial
  *    Fully functional free
  *    Open source

Supported Products *
Does this work with both Delphi and C++Builder, or just one?

  *    Delphi
  *    C++Builder
  *    InterBase
  *    RAD Studio
  *    Other:

Supported platforms *
Which compiler targets are supported

  *    Windows 32-bit
  *    Windows 64-bit
  *    macOS
  *    iOS
  *    Android
  *    Linux
  *    None

Supported GUI Frameworks *

  *    VCL Only
  *    FMX Only
  *    Both FMX & VCL supported
  *    No UI - works anywhere
  *    Console only
  *    Other:

Supported versions of RAD Studio *
What versions of RAD Studio are supported

  *    XE8
  *    10.0 Seattle
  *    10.1 Berlin
  *    10.2 Tokyo
  *    10.3 Rio
  *    Other:

Library Zip file URL *
URL to download a zip of the library to integrate into GetIt
https://github.com/Alexey-T/ATTabs/archive/master.zip

Installation process *
Describe the actions to be done to install the catalog item. Steps like copy files, compiling packages, installing packages, or running an external script or installer etc. Notice that an external installer will be executed by RAD Studio, so it cannot require RAD Studio to be closed, however you can force a reboot after the installation is completed.
Normal component installation through IDE

Uninstallation process *
Describe the actions to be done to install the catalog item. Steps like removing files, uninstalling packages, running a Windows uninstall ( please provide the uninstall package name for the OS in this case), etc.
Normal component uninstall through IDE

Thanks
We will follow up with you at your email address you provided. We appreciate your supporting us in expanding the GetIt offering and providing more value and benefits to our developers.

Any other comments or information?
Please provide any notes or comments you would like to pass along to be used in the approval or contact process. Please note here if this is an updated version, or replacing something else. Thanks!


________________________________

**Comment by Alexey-T** [comment]
Stan,
several fields must be changed!

Project name *
Name of the catalog item (short title)
ATFlatControls

Version *
Version of the catalog item
2021.06.12

Description *
Description of the catalog item for publishing in the GetIt catalog (consider space is fairly limited)
Delphi/Lazarus UI components: tabs, listbox, button, toolbar, statusbar, scrollbar. OS independent, fully custom drawn.

and URL too.

**Comment by srd-software** [comment]
OK. Now, there are a number of URLs. The project homepage URL is probably now:

https://github.com/Alexey-T/ATFlatControls

But can you confirm the others? Like the PNG link, and the vendor links. I don't know offhand what those are, or if the current ones listed are OK:

Link to image *
PNG Image to be displayed in the GetIt window. Image should be square. Recommended size is 154x154.
https://avatars0.githubusercontent.com/u/4154978?s=460&v=4

Project Homepage *
Homepage (URL) of the project or library
https://github.com/Alexey-T/ATTabs (should be https://github.com/Alexey-T/ATFlatControls now, yes?)

Vendor name *
Name of the vendor for the catalog item; for open source libraries can be name of project or team behind it
UVviewsoft.com

Vendor URL *
URL of the vendor for the catalog item (or of the open source project/team)
http://uvviewsoft.com/

Vendor Contact *
Contact URL or email to contact vendor
https://github.com/Alexey-T/ATFlatControls/issues

Library License File or EULA URL *
URL to the plain text representation of the full license file
https://github.com/Alexey-T/ATFlatControls/blob/master/license.txt

Library Zip file URL *
URL to download a zip of the library to integrate into GetIt
https://github.com/Alexey-T/ATTabs/archive/master.zip

________________________________

**Comment by Alexey-T** [comment]
> (should be https://github.com/Alexey-T/ATFlatControls now, yes?)

yes

>Vendor name *

Alexey Torgashin

>Vendor URL *

ok

>Vendor Contact *

ok

>Library License File or EULA URL *

ok

>Library Zip file URL *

https://github.com/Alexey-T/ATFlatControls/archive/master.zip

**Comment by srd-software** [comment]
OK, thanks. I'll put all this in an email to that last guy who helped us. That would be the easiest way. I'll let you know what he says.

Stan

________________________________

**Comment by srd-software** [comment]
Serge,

We have some updates and want to replace the ATTabs component in Getit. First, the name has changed to ATFlatControls. And some of the details need to be updated. ATFlatTabs should replace ATTabs and any older ATFlatTabs (if any).

I re-sent a submission form (a google form). I'm not sure if you will get it or if it will make sense that we want to replace ATTabs and any old ATFlatControls already in Getit. So, here is all the new data for you below. Any questions please let me know.

Stan

Embarcadero GetIt Submission Information
Use this form to provide information to Embarcadero Technologies to include packages, components and libraries in the GetIt catalog.

* Required
Email *
***@***.***

Introduction
If you have any questions about the process you can follow up with Jim McKeeth via ***@***.*** or on Skype as jimmckeeth.

About You
Please make sure you are a product manager or owner for anything you are submitting. For open source projects please get the primary project manager involved. There is a comments question at the end where you can explain your relationship to the project if it is complicated.

Your Name *
Stan Day

About the Project
This is how it will appear in GetIt

Project name *
Name of the catalog item (short title)
ATFlatControls

Version *
Version of the catalog item
2021.06.12

Description *
Description of the catalog item for publishing in the GetIt catalog (consider space is fairly limited)
Delphi/Lazarus UI components: tabs, listbox, button, toolbar, statusbar, scrollbar. OS independent, fully custom drawn.

Link to image *
PNG Image to be displayed in the GetIt window. Image should be square. Recommended size is 154x154.
https://avatars1.githubusercontent.com/u/4154978?s=400&v=4

Project Homepage *
Homepage (URL) of the project or library
https://github.com/Alexey-T/ATFlatControls

Tags *
Comma separated list of keywords to help the user find this entry on the catalog
tabs, listbox, button, toolbar, statusbar, scrollbar, progressbar, gauge, flat

Category *
Components

About the Company or Team
If users want more information about the company or team behind this library

Vendor name *
Name of the vendor for the catalog item; for open source libraries can be name of project or team behind it
Alexey Torgashin

Vendor URL *
URL of the vendor for the catalog item (or of the open source project/team)
http://uvviewsoft.com/

Vendor Contact *
Contact URL or email to contact vendor
https://github.com/Alexey-T/ATFlatControls/issues

Entry details
This is the nitty gritty that is used during the installation process
Library License Name *
e.g. Mozilla Public License 1.1 (MPL 1.1), commercial, trial, etc.
MPL 2.0

Library License File or EULA URL *
URL to the plain text representation of the full license file
https://github.com/Alexey-T/ATFlatControls/blob/master/license.txt

License Type *
You are free to do a "trial" version, but we've found users are less likely to download those. Instead, we recommend you do a "lite" version with an offer to upgrade to the full version. Ultimately the choice is yours.
Fully functional free

Supported Products *
Does this work with both Delphi and C++Builder, or just one?
Delphi
Other:
Lazarus

Supported platforms *
Which compiler targets are supported
Windows 32-bit

Supported GUI Frameworks *
VCL Only

Supported versions of RAD Studio *
What versions of RAD Studio are supported

10.3 Rio
10.4 Sydney

Library Zip file URL
URL to download a zip of the library to integrate into GetIt. If you don't provide a Zip file then users will be directed to your product page for installation.
https://github.com/Alexey-T/ATFlatControls/archive/master.zip

Installation process
Describe the actions to be done to install the catalog item. Steps like copy files, compiling packages, installing packages, or running an external script or installer etc. Notice that an external installer will be executed by RAD Studio, so it cannot require RAD Studio to be closed, however you can force a reboot after the installation is completed.
Normal component package installation through IDE

Uninstallation process
Describe the actions to be done to install the catalog item. Steps like removing files, uninstalling packages, running a Windows uninstall ( please provide the uninstall package name for the OS in this case), etc.
Normal component uninstall through IDE

**Comment by srd-software** [comment]
Alexey,

I sent in both a form and an email to try and get things working. I'll let you know what I hear.

Stan

________________________________

**Comment by srd-software** [comment]
Alexey,

Serge Pilko at Embarcadero has updated Getit. He had a couple of things he wanted me to pass along.

One is you can tweet about this update with the #GetIt hashtag and Serge will re-tweet it also. If you do that you can send him the link to your tweet (I can give you his email), or you can send it to me and I'll forward it to him. I do not "tweet" at all and do not have a twitter account.

Second, the Donald Duck logo will cause licensing problems for you if Disney sees it. And Embardadero has issues with it too as they do not want to get in the middle of it! Best to avoid that by replacing it asap. Use some clipart that is already licensed for free commercial use instead. If you could replace the image using the same location (URL) then we won't have to change the link to it in Getit.

Please let me know about the tweet and logo and I'll let Serge know if you like.

Stan

________________________________

**Comment by Alexey-T** [comment]
1. I don’t use Twitter 
2. Donald- of course! Please give to Serge any generic pic. From your taste, it can be letter A or letters AT or another generic pic

**Comment by srd-software** [comment]
Alexey,

Yeah, I never had interest in twitter either.

I made you a new basic image. I'll attach it. I sent it to Serge but I have a feeling you'll need to upload it someplace and then send the link to it. I can forward that link to Serge and he can update Getit.

Stan

________________________________

**Comment by srd-software** [comment]
Alexey,

Serge was able to change the logo so we should be all set.

Stan

________________________________

**Comment by Alexey-T** [comment]
Thanks..

**Comment by Alexey-T** [comment]
@srd-software Hello. If you are still here, can you update GetIt release, pls?
