### ISSUE TITLE
Middle click and drag issue

### ISSUE THREAD

**Issue by petko** [Alexey-T/ATButtons#50]
Clicking on a tab with the middle mouse button starts a tab drag, but that drag never finishes. So you are stuck in a drag mode forever.

IMO it shouldn't start drag at all..

**Comment by Alexey-T** [comment]
- What OS?
- how can I see this on atflatcontrols/app/demo_tabs ? what options of ATTabs to change?

**Comment by petko** [comment]
Windows 10 x64. I don't think that you need any additional options. I get the same behavior with a simple project without any options set.

**Comment by Alexey-T** [comment]
fixed. Reason was OptMouseMiddleClickClose=false
