### ISSUE TITLE
TabBorder width problem with High DPI

### ISSUE THREAD

**Issue by petko** [Alexey-T/ATButtons#51]
The HighDPI support is excellent, but there is a problem with tab border width. It is not scaled, but is always 1px (the routines use `DrawLine` function, which does not take width as param, but uses hard-coded 1px width). 

Can this be fixed?

**Comment by Alexey-T** [comment]
Its not easy-- line connections (angled line touches horizontal line, etc) will be not easy to make ok. Try to make a patch to DrawLine(): add there

C.Pen.Width:= DoScale(1);
....
C.Pen.Width:= 1; //after painting

also some LineTo are called in n places outside of DrawLine

**Comment by petko** [comment]
I understand. Ok, alternatively, is is possible at least there not to be a gap between the ATTabs component and the one before it? Right now, when in HighDPI mode, the bottom line is 2-3px shorter to the left. If my explanation is not good enough, I can make a screenshot.

**Comment by Alexey-T** [comment]
Screenshot pls with red arrow

**Comment by petko** [comment]
I want to create a visual effect as though the ATTabs component and the TShape line before it are one single component.

![TabBorder](https://user-images.githubusercontent.com/71472/71211871-bdb05c00-22b8-11ea-97b3-9423b8da973a.png)

**Comment by Alexey-T** [comment]
Ok, i added prop OptUnderlineWidth-- if 0 then scaled 1px used, you can set it to e.g. 12

**Comment by Alexey-T** [comment]
@petko Ok?

**Comment by petko** [comment]
@Alexey-T thanks for the update, but it does not work as expected. It also makes things worse, because some new black pixels are now visible right above the bottom line (in front and between the tabs).

Please revert the revision, I will try another way to accomplish what I am trying to do and the option won't be of help to other people anyway.

**Comment by Alexey-T** [comment]
i just changed now default of this new prop-- to 1 (looks like old code).

**Comment by petko** [comment]
By the way, which property controls the color of the area under the tab and under the bottom black line? It looks grayish, but I can't find such color in the control options and it is not the background color either (it is a little bit darker)..

**Comment by Alexey-T** [comment]
ColorTabActive. when i change it to red i get this.
![Screenshot from 2019-12-23 10-05-04](https://user-images.githubusercontent.com/4154978/71341807-f0ce4600-256b-11ea-966c-5e378b57a68c.png)

**Comment by Alexey-T** [comment]
When i set OptUnderlineWidth=7 and yellow for ColorBorderActive, i get no black bad pixels. pls show some demo and screenshot?

![Screenshot from 2019-12-23 10-10-52](https://user-images.githubusercontent.com/4154978/71342069-c3ce6300-256c-11ea-8d48-3d8e563df857.png)

**Comment by Alexey-T** [comment]
removed that new prop at all.

**Comment by petko** [comment]
Thanks!
