### ISSUE TITLE
ATTabs Issue on Lazarus Linux GTK2 close button requires two clicks

### ISSUE THREAD

**Issue by tcaduto** [Alexey-T/ATButtons#52]
Hi, 
Having a issue with ATTabs on Linux GTk2 (Laz 2.06)  When I add a tab from a popup menu from a tvirtualstringtree the close button on the tab does nothing on the first click and on the second click it closes and in the terminal this error pops up:
`GLib-GObject-WARNING **: 11:15:36.741: ../glib/gobject/gsignal.c:1206: no emission of signal "button-release-event" to stop for instance '0x208b5b0'`
If I right click on the tab and use the popup menu I call to close the tab this error does not occur.
Also if I spawn the tab from a button on a toolbar it closes on the first click but that error still shows in the terminal.   I am using the latest version of Attabs as of a day ago.
This does not happen in windows and I have not been able to test in QT5  
I am using tactions to add the tab and if I call the action from the tvirtualstringtrees double click event it also closes on the first click, it's only if the addtab is called from the context of a popup menu.   I also noticed if I click anywhere on the form that is hosted in the tab then click the close button it closes.

**Comment by Alexey-T** [comment]
Seems some gtk2 widgetset (Lazarus) issue, maybe it don’t emit some calls or smth, not sure...
