### ISSUE TITLE
Scroll tabs using mouse wheel

### ISSUE THREAD

**Issue by petko** [Alexey-T/ATButtons#53]
Do you think it would be easy to add a scrolling of the tabs via the mouse wheel like in Firefox? It will make navigating when there are many tabs much easier and faster for users.

**Comment by Alexey-T** [comment]
not sure, maybe later... I don't need it here.

**Comment by Alexey-T** [comment]
Just added, it was easy, you should did it yourself before asking :) pls test.

**Comment by petko** [comment]
Works excellent! Thanks!
