### ISSUE TITLE
Sample Code ?

### ISSUE THREAD

**Issue by JacoFourie** [Alexey-T/ATButtons#55]
Hi.

Do you have a sample where the tabs work like a TPageControl Where it will show the content of the tab yu click on? All the sample the content stays the same no matter what tab you click on.

Thanks.

**Comment by Alexey-T** [comment]
https://wiki.freepascal.org/ATTabs#How_to_use_it_like_TPageControl

**Comment by JacoFourie** [comment]
Hi. I saw that but I don't understand how to do it.

Do you not have a sample with the Frames in already? I don't know how to use frames.

**Comment by Alexey-T** [comment]
Use Forms instead of Frames. like this

var F: TForm;
begin
F:= TForm.CreateNew;
F.Parent:= MainForm;
F.Align:= alClient;
F.BorderStyle:= bsNone;
F.Show;

**Comment by JacoFourie** [comment]
How do I show the content of the form I build at design time as the tab if I creat a blank form like in your sample? And If I use more than one form as tabs how do I send data between the tabs like with a TPageContol item. With PageControl everything is in one form and I can get to each item on every tab.

**Comment by Alexey-T** [comment]
you cannot design ui on Tabs in design time. you have to design all forms as separate forms, then in RUNTIME you embed them into one host panel.

**Comment by JacoFourie** [comment]
I like your controls but I am a beginner and I don't know what you are talking about. If you had a sample with Frames or Forms that work like PageControl I would understand what you are saying.

**Comment by Alexey-T** [comment]
I made new demo
https://github.com/Alexey-T/ATFlatControls/tree/master/app/demo_tabs_as_pagecontrol
OK?

**Comment by Alexey-T** [comment]
It is for Lazarus, but you can see source code for Delphi

**Comment by JacoFourie** [comment]
Thank you very much. I am using Lazarus on the Raspberry Pi. The sample won't run. It is complaining that it can not find Interfaces in the uses clause. all your other sample work.

**Comment by JacoFourie** [comment]
OK I got it working on windows. But the app seems very slow. why would that be.
If I type text into the text box the text will lag way behind. Anyway thanks for the sample.

**Comment by JacoFourie** [comment]
OK how do you interface between the forms? 
With PageControl all items are in one form and I can get to all items with code.
Lets say there is a text item on tab3 and a button on tab1. If I click on Button on tab1 then the textbox on tab3 but show "Hello World". If I use a PageControl I do it like this.

procedure TForm1.Button1Click(Sender: TObject);
begin

  Form1.Edit1.Caption := 'Hello World";

end; 

How do I do that if you have separate forms?

**Comment by Alexey-T** [comment]
> Thank you very much. I am using Lazarus on the Raspberry Pi. The sample won't run. It is complaining that it can not find Interfaces in the uses clause. all your other sample work.

I cannot see this error here in Lazarus 2.1 trunk. linux. project uses LCL package so its ok.

**Comment by Alexey-T** [comment]
- I dont see that it's slow- all ok here on Linux
- you can write Form_Frame1.Button1.Caption:= '...' or Form_Frame3.Edit1.Text:= '..'

**Comment by JacoFourie** [comment]
This is on the Raspberry Pi.  Also using 2.1.0

![image](https://user-images.githubusercontent.com/17771641/76074085-76766500-5fa3-11ea-8353-a77abcbacd3d.png)

**Comment by JacoFourie** [comment]
OK I got it working on the Pi

![image](https://user-images.githubusercontent.com/17771641/76074682-690daa80-5fa4-11ea-8017-e5630e00a383.png)

**Comment by JacoFourie** [comment]
Thank you Alexey. You have shown me a lot about how to use your controls and how to use Forms in Lazarus. I just neet to understand this last part then I will go off and do my own thing. I updated your sample to have a button on Tab1 / Frm1 . Button1 and a Textbox on Tab2 / Frm2. I want to update the text in the textbox on Tab2 if I click on the Button on Tab1. Where do I put the code and how should I address it?

Here is the button on Tab1 called Button1

![image](https://user-images.githubusercontent.com/17771641/76075559-eab20800-5fa5-11ea-9a33-0d64218d0254.png)



Here is the text box called Edit1 on Frm2

![image](https://user-images.githubusercontent.com/17771641/76075473-c2c2a480-5fa5-11ea-916a-729eca6a90e0.png)


I also want to know if I can update items on the Forms from the main Form. Lets say data is comming into the Main Form via a Rest call. The main form will have a callback that will be called if there is data. Then I want to send that data to one of the Tabs / Forms. So for a test I will just add a timer to the main form like this . every second I want to update a text box on Tab3 from the timer event on the main form.

![image](https://user-images.githubusercontent.com/17771641/76075841-61e79c00-5fa6-11ea-86a2-3bd45eeb7b68.png)

Is what I ask possible ?

**Comment by JacoFourie** [comment]
Also, Can I call code in the main form from the 3 other forms? Let's say the main form creates a database connection and has some procedures to update the database. Can I call the code to update the database from the 3 forms/tabs?

**Comment by Alexey-T** [comment]
seems, IDE has new format of LPI file so my LPI file is read on your PC without LCL package.
my file has
```
    <RequiredPackages>
      <Item>
        <PackageName Value="atflatcontrols_package"/>
      </Item>
      <Item>
        <PackageName Value="LCL"/>
      </Item>
```

**Comment by JacoFourie** [comment]
If I try to update the textbox on Form 3 in the timer I get errors. I don't know how to reference the item

![image](https://user-images.githubusercontent.com/17771641/76077391-45992e80-5fa9-11ea-9517-81dd85ac2023.png)

**Comment by Alexey-T** [comment]
- you cannot call code in mainform from child forms
- your code "f3.Edit1.Caption:= ..." is ok, so maybe you miss smth, e.g. "Edit1" is missed on f3? use only those names which defined in f3.

**Comment by JacoFourie** [comment]
Mmm OK that is a problem then. Do I have to make a new connection on the child form then if I can not call code on Parent Form.

Here is Form 3

![image](https://user-images.githubusercontent.com/17771641/76077967-5e561400-5faa-11ea-85b3-91164e34cd47.png)

If I try to update its text I get this error. It does not see the text box.

![image](https://user-images.githubusercontent.com/17771641/76078069-98271a80-5faa-11ea-8490-27863f632a08.png)

**Comment by Alexey-T** [comment]
Reason is type of variable f3. Change it to actual type

**Comment by Alexey-T** [comment]
Access to main form- ask it at the Lazarus forum

**Comment by JacoFourie** [comment]
OK I can update the main form from the child form. I write some code now and it works. I now still need to know how to access the child form from the main form. What do you mean by "Change it to actual type" ?

**Comment by JacoFourie** [comment]
OK I got it working. Thanks a lot. Now I know how to do it all.

**Comment by Alexey-T** [comment]
F3 has actual type TFormFrame3 or the like
