### ISSUE TITLE
ATListBox Scroll Issue

### ISSUE THREAD

**Issue by srd-software** [Alexey-T/ATButtons#57]
OK, one more thing on the ATlistbox. I have it aligned alClient on a panel. The panel is just "floating" it's not aligned to anything. I have both scroll style properties set to **alssHide**. But when I show the panel in the app, it looked like the image below when it was aligned client. Note the gray box at the bottom. That's because the list decided to scroll itself up for some reason. The panel height is set to exactly the height of it's contents, but I can set the height larger than needed but it still has the issue. There should be no scrollbars or any scrolling going on

I could use the mouse wheel to scroll it back down but I don't want to have to do that! The rectangle at the top is a label aligned top, the ATlistbox is aligned client. The arrow points to the problem.

![image](https://user-images.githubusercontent.com/51385541/102697208-5988e680-41f1-11eb-9988-6bd802d44e54.png)

I could align it to none and then set all the sizes but it seemed like that shouldn't be needed. Here's what it should look like:

![image](https://user-images.githubusercontent.com/51385541/102697259-cc925d00-41f1-11eb-9ac1-9b0e6b9f7394.png)

I finally added this to line 376 of my atlistbox.pas file:
```
  if (not NeedVertBar) then
    FItemTop := 0;
```
![image](https://user-images.githubusercontent.com/51385541/102697243-a1a80900-41f1-11eb-871a-94559c245a62.png)

That has fixed it but as before, I'm not sure that's the best fix or the best place for it. When you have time could you look at it and see what you think?

Thanks Alexey.

**Comment by Alexey-T** [comment]
i answered. you need to use Theme prop, and change item of theme. Theme is a pointer to theme record. i hope it helps.

**Comment by srd-software** [comment]
This one turned out to be more an issue of setting ItemTop := 0 before showing the panel that ATlist is sitting on. Thanks Alexey!
