### ISSUE TITLE
onData event for TATListBox

### ISSUE THREAD

**Issue by daniel-sap** [Alexey-T/ATButtons#58]
When VirtualMode is set to True the DoDefaultDrawItem is writing the indexes for the items 
SLine:= '('+IntToStr(AIndex)+')';
However this is not very useful in case you want to show some meaningful data.
If onData event is present it can take the proper text.
```
if Assigned(fOnData) then
    fOnData(Self, aIndex, SLine)
  else
  if (AIndex>=0) and (AIndex<FList.Count) then
    SLine:= FList[AIndex]
  else
    SLine:= '('+IntToStr(AIndex)+')'; 
```
I see that the custom draw can do the trick, but it is overhead, cause most of the time when you are in Virtual Mode you don't want to custom draw the control, but you always want to specify the Lines

**Comment by Alexey-T** [comment]
patch is welcome.
(sorry for long delay, missed notification...)

define OnData type near
```
type
  TATListboxDrawItemEvent = procedure(Sender: TObject; C: TCanvas; AIndex: integer; const ARect: TRect) of object;
  TATListboxCalcWidth = function (Sender: TObject; C: TCanvas): integer of object;  
```
and do the testing.

**Comment by daniel-sap** [comment]
I've just double checked and see that I was wrong about the issue. Everything works fine.
(Somehow I didn't set the onData event and it was nil)

Terribly sorry! 
I saw that you removed the code in the last commits. Sorry of wasting your time.
(Next time when I create an issue will be much more cautious)
Apologize
