### ISSUE TITLE
Delphi package and ATScrollBar Addition

### ISSUE THREAD

**Issue by srd-software** [Alexey-T/ATButtons#6]
Alexey, I downloaded the flat controls and went through them to make them compile under Delphi. I was able to do that but it required a LOT of changes to remove references to lazarus related code. For this to really work, it would need your knowledge in order to put the lazarus pieces back in while keeping compile defines for delphi. Some of it I can fix, but there's a few things (especially in the gauge and listview controls) that would be faster for you to convert to delphi (i.e., "RadialPie"). And a few things like csTripleClicks, BorderSpacing and FBorderStyle calls that I keep running into would (I think) be worth converting for delphi-compatible use now and in the future.

Mostly I was/am interested in the atscrollbar control. I had a _really_ old "standalone" version of it (not sure what version or how old it was, but this one had no ATScrollbarTheme stuff in it at all). The current one has a lot of improvements (especially the ATScrollbarTheme stuff which will make it usable in my self-themed apps). I got it working with almost no lazarus issues. I added some code to allow the thumb to have colors for both over and down states and I plan to add the same color states for the arrows.

I uploaded the changed code to: https://github.com/srd-software/ATFlatControls

Would you be interested in looking at all that? If not that's OK, I can just strip the scroll bar out and make it a standalone control for now.

Stan

**Comment by srd-software** [comment]
![demo](https://user-images.githubusercontent.com/51385541/59855557-6e519900-9332-11e9-8e62-b464ac2757b0.gif)

**Comment by srd-software** [comment]
Additional ATScrollBar: make using images for thumb and arrows possible (like ATTabs).

**Comment by Alexey-T** [comment]
I will look at it, soon

**Comment by srd-software** [comment]
Fix for linklabel added (not merged, not sure how to do that).

EDIT: This control and a few others need CM_MOUSEENTER and CM_MOUSELEAVE added to them (the linklabel change was for this). I'm wondering if it might be better to put those into an include file? Might take several include files as pieces of related code go into type private, protected, and published. 

Also, not sure how to deal with icons.lrs. It looks like it's just holding the bitmaps in the same folder. OK, looks like they are used for the registration stuff. I'll see if I can figure that out for the delphi package.

**Comment by srd-software** [comment]
OK, got the package resources fixed (also for attabs package, will have to do an update here).

**Comment by Alexey-T** [comment]
You can add $ifdef's for all CM_ messages for Delphi (for Lazarus it must be OnMouseEnter/OnMouseLeave)

**Comment by Alexey-T** [comment]
Best if you post fix for scrolbar as separate patch (for mouse over colors)
Later - Delphi fixes

**Comment by Alexey-T** [comment]
Can you first make patch which adds Delphi compat? Later I will add patch for new colors?

**Comment by Alexey-T** [comment]
I will look at your repo

**Comment by Alexey-T** [comment]
I ask to rework your fork

- all laz code must be in {$ifdef FPC}, not deleted

- keep my end of lines (LF?) so GH will not  think all file is new

**Comment by Alexey-T** [comment]
- Delphi only code must be in {$ifndef FPC} or use {$else}

**Comment by Alexey-T** [comment]
I want to see on GH site your changes as red parts

**Comment by srd-software** [comment]
OK, still working on it all.

**Comment by srd-software** [comment]
I went through it and did the best I could. I tried to keep line ends the same but there are going to be differences. This one does compile OK in delphi. The scrolbar works well. The other controls load and seem OK but I don't know about their functionality yet. Let me know if you can work with this. I know it's messy! #7

**Comment by srd-software** [comment]
I'm sure this needs work. If you can let me know what to look for and how best to fix I'll keep working on it.

**Comment by srd-software** [comment]
OK, I'm running the new controls in my fpc, so I'm finding things that way. Looks like {$ifdef windows} needs to be {$ifdef delphi}.  I'm making progress.

**Comment by Alexey-T** [comment]
See my comments in pull req

**Comment by srd-software** [comment]
OK, whole new set of files. This one should be closer. I used both lazarus and delphi and went back and forth changing the code as needed. Now both compile, demos in lazarus work, and my demo works. Still be some work (e.g., I can't get the atlistbox to scroll in delphi app, it works, items add, but no scrolling). Atscollbar works in both. I had to add the same lazarus-style mouseenter/leave into it but it looks nice now on mouseovers in both lazarus and delphi..

#8

**Comment by srd-software** [comment]
Got the scrolling on the listbox. Still had the wrong compile flag in there. (files up now don't have that fix but will deal with it later).

**Comment by Alexey-T** [comment]
made NNN comments.
pls see while scrolling your changes.
https://github.com/Alexey-T/ATFlatControls/pull/8/files

**Comment by srd-software** [comment]
That's what I've been looking at. I just don't see any indications of comments on the screen. Everything looks like the image below. Is there something to hover over or click to bring up comments?

![Image29](https://user-images.githubusercontent.com/51385541/59882634-015cf400-9370-11e9-8a17-084c62f2ce4a.png)

**Comment by Alexey-T** [comment]
I did not press Submit, now I pressed it, do you see?

**Comment by srd-software** [comment]
Yes! Success! OK, let me take a look at these and work on that.
