### ISSUE TITLE
atflatcontrols_separator

### ISSUE THREAD

**Issue by hosekb** [Alexey-T/ATButtons#60]
Hi,
I have problem with atflatcontrols_separator.pas on Delphi 10.
Bohous

**Comment by Alexey-T** [comment]
can you post error log from IDE?

**Comment by hosekb** [comment]
Yes, of course ...

1.
{$mode objfpc}{$H+}
{$ModeSwitch advancedrecords}

correct to
{$ifdef FPC}
---
{$endif}

2.
[dcc32 Error] atflatcontrols_separator.pas(28): E2254 Overloaded 
procedure 'GetItemStr' must be marked with the 'overload' directive
[dcc32 Error] atflatcontrols_separator.pas(29): E2252 Method 
'GetItemStr' with identical parameters already exists
[dcc32 Error] atflatcontrols_separator.pas(30): E2254 Overloaded 
procedure 'GetItemInt' must be marked with the 'overload' directive
[dcc32 Error] atflatcontrols_separator.pas(32): E2003 Undeclared 
identifier: 'DWord'
[dcc32 Error] atflatcontrols_separator.pas(32): E2005 'DWord' is not a 
type identifier
[dcc32 Error] atflatcontrols_separator.pas(70): E2004 Identifier 
redeclared: 'TATStringSeparator.GetItemStr'
[dcc32 Error] atflatcontrols_separator.pas(116): E2005 'DWord' is not a 
type identifier
[dcc32 Error] atflatcontrols_separator.pas(116): E2005 'DWord' is not a 
type identifier
[dcc32 Error] atflatcontrols_separator.pas(122): E2003 Undeclared 
identifier: 'StrToDWordDef'
[dcc32 Error] atflatcontrols_separator.pas(28): E2065 Unsatisfied 
forward or external declaration: 'TATStringSeparator.GetItemStr'

------ Původní zpráva ------
Od: "Alexey T." <notifications@github.com>
Komu: "Alexey-T/ATFlatControls" <ATFlatControls@noreply.github.com>
Kopie: "hosekb" <hosekb@gmail.com>; "Author" <author@noreply.github.com>
Odesláno: 09.02.2021 16:01:44
Předmět: Re: [Alexey-T/ATFlatControls] atflatcontrols_separator (#60)

**Comment by Alexey-T** [comment]
made fixing from your report, please check now.
