### ISSUE TITLE
ATTABS new version ellipse issue

### ISSUE THREAD

**Issue by srd-software** [Alexey-T/ATButtons#63]
Hi Alexey,

I have a strange issue with the latest version of ATTABS. If I have tabs with no ellipsis in them the tab captions are OK. However, if the tab captions are longer than will fit in the tabs, I get odd characters where I should be getting ellipsis (should be these: ... ). I'll put in some screen shots below. The first one is how it _should_ look, the second one is what I'm now getting. As far as I can see in my code, I'm not drawing any text myself, it's all in the tab control. If I maximize the app so some of the tabs no longer need ellipsis, those tabs are then OK until I restore the app to normal size. I have no idea what the problem is or even where to start looking! 

CORRECT:

![image](https://user-images.githubusercontent.com/51385541/107857400-70ac1500-6deb-11eb-83e6-7062ac5b2aa0.png)

The one below is INCORRECT and what I get with the latest version:

![image](https://user-images.githubusercontent.com/51385541/107857422-920d0100-6deb-11eb-9ea5-ddf7f0b34721.png)

**Comment by Alexey-T** [comment]
UTF8Decode / UTF8Encode is missed for rendeding... will check it..
What Delphi version?

**Comment by Alexey-T** [comment]
check ATCanvasPrimitives.pas
is it in OK coding? dots is OK?
```
function CanvasCollapseStringByDots(C: TCanvas;
  const Text: string;
  Mode: TATCollapseStringMode;
  Width: integer;
  DotsString: string='…'): string;
const                                   
```

**Comment by Alexey-T** [comment]
did my fix help?
@srd-software

**Comment by srd-software** [comment]
> check ATCanvasPrimitives.pas
> is it in OK coding? dots is OK?
> 
> ```
> function CanvasCollapseStringByDots(C: TCanvas;
>   const Text: string;
>   Mode: TATCollapseStringMode;
>   Width: integer;
>   DotsString: string='…'): string;
> const                                   
> ```

My ATCanvasPrimitives.pas has that function in it. Do I need to call that from my app somewhere?

**Comment by Alexey-T** [comment]
no, please test my fix (added today).

**Comment by srd-software** [comment]
Oh, OK. I'll try it and let you know in a minute.

**Comment by srd-software** [comment]
OK, yes, that's working now and so is the cursor! Thanks Alexey
