### ISSUE TITLE
Question ATTabs: version history?

### ISSUE THREAD

**Issue by klaus101** [Alexey-T/ATButtons#67]
Short question:
where can i find the information about recent functional changes / improvements?
Whe information within that link:
https://wiki.freepascal.org/index.php?title=ATTabs&action=history
does not appear to be very recent.  - Thank you!

**Comment by Alexey-T** [comment]
File history.txt in this repo?

**Comment by klaus101** [comment]
Ouch yes, i missed that, very silly. Thanks a lot!

**Comment by klaus101** [comment]
Is abnsered of course
