### ISSUE TITLE
ATTabs - Slight Rounding

### ISSUE THREAD

**Issue by rayhester** [Alexey-T/ATButtons#68]
Alexey

Thank you for your excellent controls, I appreciate your work.

Has there been a subtle change to how tabs are drawn?
I used to be able to get perfectly square corners by setting OptSpaceSide to 0,
but having updated to 2.1.0.0 using Online Package Manager it
appears to my (old) eyes that they now have a very slight rounding.

Hope I am not wasting your time.

Regards

Ray

**Comment by Alexey-T** [comment]
Thank you. it is new option OptTabRounded=true.

**Comment by rayhester** [comment]
Nice addition. You never rest!
