### ISSUE TITLE
Inline title edit

### ISSUE THREAD

**Issue by petko** [Alexey-T/ATButtons#69]
I don't know if this would be too technically challenging, but it would be great, if we can edit the tab title inline as for example Ms OneNote allows. I.e. option when double clicking on the tab an inline text editor shows. Of course this will also need a corresponding event to accept/reject invalid tab names and a method to pragmatically start the inline editor.

![Capture](https://user-images.githubusercontent.com/71472/119221074-422e8c00-baf6-11eb-982c-99c03b1252e4.png)

**Comment by Alexey-T** [comment]
I think ATTabs don’t need it coz program can show this input by itself! We just need to get Rect of text label of a tab. Look at the GetTabData method which gets data object. Object needs a Rect field. Try to add the needed Rect to this Data, make a patch, or I will try that

**Comment by Alexey-T** [comment]
Added field TabCaptionRect to Data (use GetTabData(n) to get it, new rect is set after tab is painted).
test it. It is relative to Tabs control.

**Comment by petko** [comment]
Thanks, I think with the TabCaptionRect and TabDblClick it should be possible to accomplish the inline editing. I will need more time, but I will try to add it as a patch.

**Comment by Alexey-T** [comment]
As a ATTabs patch? No no

**Comment by petko** [comment]
If you do not need this functionality in ATTabs, I will do a patch only for myself.

**Comment by Alexey-T** [comment]
That is okay
