### ISSUE TITLE
ColorTabActive paint regression

### ISSUE THREAD

**Issue by petko** [Alexey-T/ATButtons#70]
I've noticed a small problem with the painting of the space below tabs. In previous versions of the component the remained space below the tabs is painted with the `ColorTabActive` color as is the active tab itself.

In the current version this is also the case as long as all tabs fit in the tab control:
![SpaceForAll](https://user-images.githubusercontent.com/71472/120097736-e047d500-c13a-11eb-8a8f-30ea680f04f0.PNG)

However, if there is not enough space for the tabs, the `ColorTabActive` is no longer used:
![NotEnoughSpace](https://user-images.githubusercontent.com/71472/120097747-edfd5a80-c13a-11eb-81b4-252254705bd3.PNG)

Could this be fixed somehow?

**Comment by Alexey-T** [comment]
problem is in DoPaintSpacerRect(),
it needs fixed 1st line
```
  if FOptMultiline and FScrollingNeeded then exit;    
```
