### ISSUE TITLE
Memory leak in TATTabs?

### ISSUE THREAD

**Issue by DomenicoMammola** [Alexey-T/ATButtons#73]
Hi Alexey,
I've found a very strange memory leak that I tryed to investigate without success. It seems to be related to the
 last version of TATTabs component even if I'm not pretty sure.
However, here you can find a really simple test application that recreates the issue.
This test application creates a TATTabs instance at runtime and shows two buttons that add a simple tab to the component, with and without the memory leak.
I've tested it only under Windows 10 and Lazarus 2.0.8: the components are not installed in the IDE, source code must be available in a folder listed in the source path option of the project.
Thanks for your support and for your powerful and beautiful components,
Domenico

[test.zip](https://github.com/Alexey-T/ATFlatControls/files/7144255/test.zip)

**Comment by Alexey-T** [comment]
I just added 'atflatcontrols' to project require-list here:
![Screenshot from 2021-09-10 17-06-18](https://user-images.githubusercontent.com/4154978/132866364-4bf15be1-bf62-44b1-9e7f-e78359733f69.png)

I will look at it

**Comment by Alexey-T** [comment]
It is the mem leak. But I am not sure it's inside ATTabs. We talked about it already -
https://forum.lazarus.freepascal.org/index.php?topic=53815.0
I don't have a fix....

**Comment by Alexey-T** [comment]
Fixed! see my simple patch linked above.

**Comment by DomenicoMammola** [comment]
Thanks!!
