### ISSUE TITLE
Drag/drop from other controls not working

### ISSUE THREAD

**Issue by petko** [Alexey-T/ATButtons#74]
I've just discovered an issue. It is no longer possible to drag items from other controls to the ATTabs control. We use that to allow users to automatically switch between tabs when dragging other items from our UI.

I think that the dragging is disabled here (my tests show that it works in 2021.03.05, but not since 2021.04.01):
https://github.com/Alexey-T/ATFlatControls/commit/b3ebae4774b2604c720a35964236bbc12214c39e

Is is possible to enabled it again?

**Comment by Alexey-T** [comment]
Can you test this change- in __that__ commit change - change that line to
```
if Source is TATTabs then
  Accept:= False 
else
  inherited;
```

**Comment by Alexey-T** [comment]
Added new prop (turn it to True), see the patch linked above. OK?

**Comment by petko** [comment]
It works with this new property. However in https://github.com/Alexey-T/ATFlatControls/commit/b3ebae4774b2604c720a35964236bbc12214c39e you state that it fixes something. What does it fix and should I be aware of it when using this new property?

**Comment by petko** [comment]
Sorry, I was too quick to tell that is was fixed. While the cursor shows that you can drag now, the OnDrag event of the tabs control is still not fired..

**Comment by Alexey-T** [comment]
>However in b3ebae4 you state that it fixes something. What does it fix and 

some internal behaviour of CudaText.

>should I be aware of it when using this new property?

no.

>the OnDrag event of the tabs control is still not fired..

are you sure??? I checked in debugger, - with demo_groups demo (it was updated minute ago). when I drop TTreeNode on tabs, the IDE debugger shows that this block works
```
procedure TATTabs.DragDrop(Source: TObject; X, Y: integer);
begin
  if not (Source is TATTabs) then
  begin
    inherited;
    exit;
  end;
          
```
this block calls inherited! it calls TControl.OnDragDrop

**Comment by petko** [comment]
I am talking about `OnDragOver` event that is not working. `OnDragDrop` works.

**Comment by Alexey-T** [comment]
Now I fixed this too, pls check.

**Comment by petko** [comment]
I can confirm that both work now. Thank you very much!
