### ISSUE TITLE
Font scaling correction

### ISSUE THREAD

**Issue by petko** [Alexey-T/ATButtons#75]
It looks like we need a small font scalling correction in order the tabs font to be scaled properly when the control is moved between monitors with different DPI:

https://github.com/Alexey-T/ATFlatControls/blob/c536aa6b621138a59c2509ca1aad13cc1431bfe3/atflatcontrols/attabs.pas#L1601

should be

`C.Font.Height:= DoScaleFont(C.Font.Height);`

`Size` is in points, `Height` is in pixels, so we need to use `Height` here. Currently the tab text is truncated if the control is moved to a monitor with different DPI.

**Comment by Alexey-T** [comment]
Is this issue still valid? I overlooked it. sorry.

I don't get idea of that fix (you wrote it).
Why we cannot do 'size:= ...size' and must do 'height:= ...height'?
it must be the same!

**Comment by petko** [comment]
I can't check right now, because I don't have a second monitor, but I am pretty sure the problem persists.

I think that using `Height` fixes the problem when moving between monitors, because `Size` is measured in points and `Height` is in pixels. However I am not sure in the details of this and why it works exactly..

**Comment by Alexey-T** [comment]
After you check the fix, I can apply it.

@veksha Hi, do you have 2 monitors? can you set different DPI for them, and test the fix in the 1st post?

**Comment by veksha** [comment]
Hi. how to repro issue? what OS?
can I see screenshot?

on Windows right now. All seems OK.

**Comment by Alexey-T** [comment]
@petko I don't know how to reproduce issue, I am on linux and I have same DPI for 2 monitors. Pls answer to veskha.

**Comment by petko** [comment]
I will have access to a second monitor with lower DPI later today or tomorrow and will try to reproduce it and post screenshots here.

**Comment by Alexey-T** [comment]
@petko Applied the fix from the 1st post. Better now?

**Comment by petko** [comment]
Perfect!
