### ISSUE TITLE
Question about buttons placed on the left side and tabwidth of the leftmost tab after scrolling

### ISSUE THREAD

**Issue by klaus101** [Alexey-T/ATButtons#76]
I'm using the ATTabs / Lazarus since nearly a year with fun :-)

For a little usage change i did run into the following question (no issue):

I'm using OptVarWidth true, OptTabWidthMinimal := 80,
and now - testing: -   the button for tab scrolling as well as the button for tab list both on the left side (OptButtonLayout:= '<> v'):

Is there an already existing capability to define a certain min-width for the (after scrolling:) leftmost appearing tab?
So that we can be avoid to have truncation effects like the two ones shown in the picture?

![grafik](https://user-images.githubusercontent.com/31130146/156792620-4e4853d7-6c1c-475d-a7fc-e82c55a68a90.png)

Use case would be that the leftmost appearing tab is at least recognizable after scroll.
One might keep in mind that when placing scroll and list buttons both on the left side the user's "operational focus" is surely on the left side.

**Comment by Alexey-T** [comment]
i think no such a feature - ie we always have partially scrolled tab. it may be not connected with OptButtonLayout. not sure. can you place all <>v buttons on the right?

**Comment by klaus101** [comment]
Thank you Aleeey for attention!
Yes, i could (via ', <> v'), but why i tried at left?
Actually i have/had one (for list) on the left and the other (for scroll) on the right side, and, over the time, i felt that's not so much efficient.
So i tried to concentrate both at the left, because eyes, attention and mouse are foucsed more on the left placed objects in the listview underneath, rather than on the secondary listview's item attributes on the right side.
Therefore left.
 
But you are right, maybe it's even better to have both concentrated on the ride side rather to have them spreaded along two sides. I'll give it a try.
As said, it's not an issue at all, only a little use case test. There are already so many options available :-)

**Comment by Alexey-T** [comment]
i am not sure 'how hard' is it to make the fix (for the buttons on the left). it needs reading the code...

**Comment by Alexey-T** [comment]
i was busy with CudaText proj, and forgot the Tabs code a little.
