### ISSUE TITLE
Can't compile ATCanvasPrimitives in 10.4

### ISSUE THREAD

**Issue by raelb** [Alexey-T/ATButtons#78]
![image](https://user-images.githubusercontent.com/13108198/169828109-72f666f4-dbe7-4288-b87b-7fd33498b22f.png)

**Comment by Alexey-T** [comment]
submitted the fix. BTW, in what project do you use it? :)

**Comment by raelb** [comment]
So far not - just trying the components out. I will let you know if I do.

There are more errors:

![image](https://user-images.githubusercontent.com/13108198/169849836-eabe2f66-138b-4768-986d-398d5fec2afa.png)

**Comment by Alexey-T** [comment]
made the fix, any more errors?

**Comment by raelb** [comment]
Thanks, working now!
