### ISSUE TITLE
How put a form insde tTab or controls like tpage

### ISSUE THREAD

**Issue by eldonfsr** [Alexey-T/ATButtons#79]
Hello how is possible to put form inside TTab or Controls like tpage, for example on ABM of table if i create a form with control how i put that inside ttab, on examples you i don't see  some like add a tab or page the way can add controls there...

**Comment by Alexey-T** [comment]
Wiki tells it
https://wiki.freepascal.org/ATTabs#How_to_use_it_like_TPageControl

**Comment by eldonfsr** [comment]
Hi this code but i received error
```
var
  df: TATTabData;
begin
  ATTabs1.AddTab(-1,'New', nil, false);
  df:= ATTabs1.GetTabData(ATTabs1.TabCount-1);
 if Assigned(df) then begin
      (df.TabObject as TFrameClie).Show;
      FrameClie1.Memo1.Lines.Clear;
      FrameClie1.Memo1.Lines.Add('Test Texto');
 end else begin
     (df.TabObject as TFrameClie).Show;
 end;            
```
On show send me error..

**Comment by Alexey-T** [comment]
in the AddTab() call you didn't pass the non-nil object.
