### ISSUE TITLE
TATTabs: Missing Event while reordering Tabs

### ISSUE THREAD

**Issue by SilentDude80** [Alexey-T/ATButtons#81]
Hi,

I am looking for an event, that is fired **_while_** the user is moving a tab to another position - basically it should fire every time when that little red indicator line changes to another tab position:

![image](https://user-images.githubusercontent.com/17182500/173750809-bfe34743-e5b9-489f-9c7f-325e02f71b14.png)

All events I could find so far are fired only **_after_** the user releases the left mouse button.

**Comment by Alexey-T** [comment]
Added OnTabDragging, pls test it.

**Comment by SilentDude80** [comment]
Wow, thank you for that fast reply and enhancement. 
It basically works, but I noticed two things:

- The OnTabDragging event fires every time the mouse is moved, even if the TabIndex does not change while dragging the mouse. Could you adjust it that it fires only if the index really would change after releasing the mouse button ?

- I forgot about a little modification that I did by myself to the previous version of ATFlatControl, which of course was removed again after installing/overwriting the old version with your new one, and so the program did not compile.
 I just added a 

`   property Tag:integer read FTag write FTag;`

to the public section of TATTabData class to be able to store a reference to e.g. an array index or database index. Could you also include that into your official code or do you know a more easy way that such code modifications are not lost ?

**Comment by Alexey-T** [comment]
Made the changes-- pls check is it ok? Added Tag too.

**Comment by SilentDude80** [comment]
Works perfectly now ! Thanks a lot !

**Comment by SilentDude80** [comment]
Hi Alexey - i came across a problem: 

The event does not fire, when the tab insertion indicator moves again to it's original position/index - i would need the event there too...

Thank you !

**Comment by Alexey-T** [comment]
I added indicator of OnTabDragging to the app/demo_tabs program. it shows line like 'OnTagDragging: 2 -> 3' on the bottom of the form. I cannot see your issue - I see indicator always. even when I return to original drop-index.

ie I see
- 2 -> 2 initially
- 2 -> 3 when I move mouse righter
- 2 -> 2 when I mose mouse back

**Comment by SilentDude80** [comment]
Sorry, was a problem in my own code - event is working fine like you said.
