### ISSUE TITLE
Little problem again

### ISSUE THREAD

**Issue by hosekb** [Alexey-T/ATButtons#82]
[dcc32 Error] atstatusbar.pas(901): E2003 Undeclared identifier: 'Move'

function TATStatus.MovePanel(AFromIndex, AToIndex: integer): boolean;
begin
  Result:= false;
  if AFromIndex=AToIndex then exit;
  if not IsIndexOk(AFromIndex) then exit;
  if not IsIndexOk(AToIndex) then exit;
  FItems.Move(AFromIndex, AToIndex);     <--- row 901 !
  Invalidate;
  Result:= true;
end;

**Comment by Alexey-T** [comment]
Fixed?

**Comment by hosekb** [comment]
All is OK, thanks

**Comment by Alexey-T** [comment]
In what project do you use ATFlatCtl?

**Comment by hosekb** [comment]
I use ATFlatControls components in many projects. These are mostly DELPHI 10/Oracle/Python 3,10 database applications. Most often I use TATTabs to display information from tables. It is my quite favorite component.
Yours sincerely
B.
