### ISSUE TITLE
How to change the position of dropdown list of a ATComboEdit?

### ISSUE THREAD

**Issue by 0001-Yong** [Alexey-T/ATButtons#85]
I want to change the width of the dropdown list to Top or bottom. 
![image](https://user-images.githubusercontent.com/32485319/210521493-71eb370c-1613-47f4-9ccd-7ea03af18284.png)

**Comment by Alexey-T** [comment]
this dropdown list is made via TMenuItem. we cannot change its width.

**Comment by Alexey-T** [comment]
position can be changed only a little. to the TPoint (x,y). then OS shows menu as it wants.

**Comment by 0001-Yong** [comment]
Hi Alexey-T , How to change  dropdown list to bottom?

**Comment by Alexey-T** [comment]
list cannot be changed to bottom. OS draws it like it wants.

**Comment by Alexey-T** [comment]
atsynedit_edits.pas
Change it here
```pascal

procedure TATComboEdit.DoComboMenu;
...
  P:= Point(Width, 0);
  P:= ClientToScreen(P);

  FMenu.PopUp(P.X, P.Y);
end;                        
```

**Comment by 0001-Yong** [comment]
Cool Thanks ! I try to create dark mode component
