### ISSUE TITLE
Bug report in TabChangeQuery

### ISSUE THREAD

**Issue by WangPingGang** [Alexey-T/ATButtons#86]
The code like this

```
procedure TForm1.ATTabs1TabChangeQuery(Sender: TObject; ANewTabIndex: Integer;
  var ACanChange: Boolean);
begin
  MessageBox(Handle, 'content has changed, save it?', 'APP_TITLE', MB_YESNOCANCEL + MB_ICONQUESTION)
end;

procedure TForm1.FormCreate(Sender: TObject);
begin
  ATTabs1.AddTab(0, 'aaaaa');
  ATTabs1.AddTab(1, 'aaaaa');
  ATTabs1.AddTab(2, 'aaaaa');
end;
```

change the tab, press any button in messagebox, now hovering the mouse to the tab, like you were trying to drag-and-drop and can not cancel.

**Comment by Alexey-T** [comment]
did you try to call `MouseUp` method in your TabQuery handler?
'protected' method - so yuo need the helper class like `type TATTabsHack = class(TATTabs)`

**Comment by WangPingGang** [comment]
> did you try to call `MouseUp` method in your TabQuery handler?

no, you can copy my code and reproduce it easy.

**Comment by Alexey-T** [comment]
I made the fix. do `git pull` and test.
