### ISSUE TITLE
Case where changed Data.TabHint is not reliably propagated to tab's hint

### ISSUE THREAD

**Issue by klaus101** [Alexey-T/ATButtons#87]
Lazarus 2.3.0 Win x64.
Let's say there's the situation where you trigger an active tab's caption change due to an external action (eg. a file or folder change monitor).
The Data.TabCaption will be adapted, the Data.TabHint adapted accordingly, but the Hint window still does show the "old" hint.
Here is a sample of the triggered code:

```
procedure TPageControlExt.UpdateCurrentTabCaption(newcapt: String);
var Data: TATTabData;
begin
  Data := FATtabs.GetTabData(FATtabs.TabIndex);
  Data.TabCaption := newcapt;
  Data.TabHint := Data.TabCaptionFull;
  //Application.HideHint;
  //Application.ActivateHint(Mouse.CursorPos);  // with optional params true, false no difference
OutputDebugString(PChar('Caption:  ' + Data.TabCaption + '  Captionfull:  ' + Data.TabCaptionFull + '  Hint:  ' + Data.TabHint ));
end;
```
  
All items debugged are correct! But the Hint Window still does show the old contents.
If i (termporarely for test) move the mouse to another tab and let it's hint show, then, when going back to the active tab now, it's hint will show correctly the new TabHint.

===> A change of the TabHint should reliably be propagated to the application's hint.

**Comment by Alexey-T** [comment]
Made the commit: added method ApplyTabHintToControlHint. solve the issue by calling it, OK?

**Comment by klaus101** [comment]
Would match my own thoughts, but it still does not work reliably. It may happen that the hint is not shown resp. is empty) after a second rename action ... .

I had identified (in TATTabs.MouseMove) this condition to be hindering in this case for to refresh the Hint:
  ` if FTabIndexHinted<>FTabIndexHintedPrev then`

So for test i added the following reset of FTabIndexHintedPrev to your code, and now it works as expected:

```
procedure TATTabs.ApplyTabHintToControlHint(ATabIndex: integer; var AData: TATTabData);
begin
  FTabIndexHintedPrev := -1;
// . . .

```
What do you think?

**Comment by klaus101** [comment]
Forgot to meniton: i do an explicit call of UpdateCurrentTabCaption in my using routine:

```
procedure TPageControlExt.UpdateCurrentTabCaption(newcapt: String);
var Data: TATTabData;
begin
  Data := FATtabs.GetTabData(FATtabs.TabIndex);
  Data.TabCaption := newcapt;
  Data.TabHint := Data.TabCaptionFull;
  FATtabs.ApplyTabHintToControlHint(FATtabs.TabIndex, Data);
end;

```

**Comment by Alexey-T** [comment]
Your fix was not fully ok (moving mouse over ui-tab in CudaText gave hint flicker).
fixed, pls test.

**Comment by klaus101** [comment]
Yes, i understand this side impact ...
Interestingly, my original idea had been to simply expose a function that allows to reset FTabIndexHintedPrev, what is basically the same. I didn't propose because that does not support an very intuitive understand of it's sense and purpose.

Your latest update works fine and, imo, understandable as well.
The minimalistic use case example now would look like:


```
procedure TPageControlExt.UpdateCurrentTabCaption(newcapt: String);
var Data: TATTabData;
begin
  Data := FATtabs.GetTabData(FATtabs.TabIndex);
  Data.TabCaption := newcapt;
  Data.TabHint := Data.TabCaptionFull;
  FATtabs.ApplyTabHintToControlHint(FATtabs.TabIndex, Data, True);
end;
````

**Comment by Alexey-T** [comment]
Can you show screenshot of your app with tabs?

**Comment by klaus101** [comment]
Ok .. As i just was trying the dark mode, a screenshot / dark mode.

![appsample_img](https://user-images.githubusercontent.com/31130146/235475280-246ef418-37a8-4316-bb33-66ff39601030.jpg)

In bright mode the tabs are looking as of this image:

![tabs_sample_light](https://user-images.githubusercontent.com/31130146/235475315-f67d26a7-fa08-47fc-b4d8-b30490a21ac5.jpg)

**Comment by Alexey-T** [comment]
Looks good. Tks.

**Comment by klaus101** [comment]
Thanks to your excellent component that makes it possible!
