### ISSUE TITLE
Delphi 11 + TAntialiasingMode

### ISSUE THREAD

**Issue by kazuser** [Alexey-T/ATButtons#89]
![image](https://github.com/Alexey-T/ATFlatControls/assets/3335273/b666207a-e9ed-4607-9839-670198734e90)

**Comment by Alexey-T** [comment]
thanks, I added the IFDEF for these lines. OK now?

**Comment by kazuser** [comment]
![image](https://github.com/Alexey-T/ATFlatControls/assets/3335273/6d1e62b5-6cf2-4b35-aa23-12503170e1c2)

**Comment by Alexey-T** [comment]
added new IFDEF. OK now? I am on linux so I cannot check it.

**Comment by kazuser** [comment]
![image](https://github.com/Alexey-T/ATFlatControls/assets/3335273/e243c4fc-be22-4a29-95b3-b2b7580dd26a)

**Comment by Alexey-T** [comment]
can you show screenshot of your app with my component? Pls.

**Comment by kazuser** [comment]
![image](https://github.com/Alexey-T/ATFlatControls/assets/3335273/ca7822c8-97f9-44ab-bf1d-30da7d037179)

**Comment by Alexey-T** [comment]
no screenshot of a final app?

**Comment by kazuser** [comment]
![image](https://github.com/Alexey-T/ATFlatControls/assets/3335273/5c01fa63-f336-431e-afc3-c19a6c79f831)
