### ISSUE TITLE
Delphi Package Functionality

### ISSUE THREAD

**Issue by srd-software** [Alexey-T/ATButtons#9]
I have a couple of things (delphi side) that, so far, I can't figure out:

- atButtons: Added the delphi mouse enter/leave code. Works OK if button is not flat, but if it's flat, background highlights correctly on enter but never goes back on leave.
- atListbox: Scrolling is better, but listbox does not respond to keyup or keydown. I can select items OK but can't use arrow keys.

This is for when we get the overall new stuff uploaded.

**Comment by srd-software** [comment]
atListBox: OK when hottrack is false, if hottrack is true the atscrollbar jumps around on mousemove. I tried to track this down but no luck. I also temporarily removed all the new atscrollbar highlighting and that did not fix so shouldn't be the cause.

I think I found this one:
```
procedure TATListbox.MouseMove(Shift: TShiftState; X, Y: Integer);
begin

  inherited;

  if FHotTrack then
  begin
    //only update when needed:
    if FHotTrackIndex <> GetItemIndexAt(Point(X, Y)) then
    begin
      FHotTrackIndex:= GetItemIndexAt(Point(X, Y));
      Invalidate;
    end;
  end
  else
    FHotTrackIndex:= -1;
end;
```

**Comment by srd-software** [comment]
- atListbox: Scrolling is better, but listbox does not respond to keyup or keydown. I can select items OK but can't use arrow keys.

Since atListBox is a TCustomControl and not a TCustomListBox, arrow keys need a WMKeyDown message to process. I now have this working.

**Comment by Alexey-T** [comment]
Okay

**Comment by srd-software** [comment]
- atButtons: Added the delphi mouse enter/leave code. Works OK if button is not flat, but if it's flat, background highlights correctly on enter but never goes back on leave.

I put a "fix" in for this in TATButton.PaintTo. Not sure it's right, but it's working in both IDEs.

**Comment by srd-software** [comment]
Added minimal fixes to atgauge. I can't find a RadialPie equivalent. Maybe you can figure that one out. If not we could remove that kind (gkpie) from the delphi version.

**Comment by Alexey-T** [comment]
Applied all stuff. made fixes then. ATButton Flat didn't paint flat in Laz (reverted your change)
