### ISSUE TITLE
ATStatusBar.pas - Delphi 10.2

### ISSUE THREAD

**Issue by hosekb** [Alexey-T/ATButtons#90]
Error in ATStatusBar.pas:

procedure TATStatus.DoPaintPanelTo(C: TCanvas; ARect: TRect;
  AData: TATStatusData; AMouseOver: boolean);

[dcc32 Error] atstatusbar.pas(392): E2003 Undeclared identifier: 'StretchDraw'

Bohous

**Comment by Alexey-T** [comment]
Posted the fix.
