### ISSUE TITLE
OptMouseDragOutEnabled broken?

### ISSUE THREAD

**Issue by petko** [Alexey-T/ATButtons#92]
If I uncheck the `OptMouseDragOutEnabled` option, then you can't drag tabs even inside the same `ATTabs` control. Can you check that?

**Comment by Alexey-T** [comment]
Yes, confirmed.
DragOver method checks this
```
  if Source is TATTabs then
  begin
    Accept:=
      FOptMouseDragEnabled and
      FOptMouseDragOutEnabled and
      ((Source<>Self) or IsDraggingAllowed);  
```
Can you make the fix, pls? But not so simple as removing the line in the shown block.

**Comment by Alexey-T** [comment]
Made the fix. Pls, test it.

**Comment by petko** [comment]
Works as expected!
