### ISSUE TITLE
Drag marker shown at left click on active tab

### ISSUE THREAD

**Issue by klaus101** [Alexey-T/ATButtons#94]
Alexey, i just upgraded my attabs files (attabs.pas, atflatcontrols_separator.pas, atcanvasprimitives.pas, attabs_picture.pas) to the recent version dated 2024/01/23. My previously used files were as of 2023/05/01.

When left clicking onto the active tab, I now see this (see video):

https://github.com/Alexey-T/ATFlatControls/assets/31130146/2288e6ae-e789-4b1c-85c9-a8c61096d8d6

By guessing it could have something to do with this change:  „Drag marker shown after context menu #93“
Apparently i now have the opposite: “Drag marker shown at left click on active tab”.
Could you give any advice? Thanks in advance!

**Comment by klaus101** [comment]
I think i found the culprit: latest change within TATTabs._IsDrag::

```
function TATTabs._IsDrag: boolean;
begin

// -- BEFORE 2024/01/23:  This worked for me far better / ... OK
  Result:= Dragging and FMouseDragBegins;

// -- WITH 2024/01/23: probably reason for "Drag marker shown at left click on active tab":
  Result:=
    {$ifdef FPC}
    DragManager.IsDragging; //better check than commented code below: it works when drag was started in another control
    //Dragging and FMouseDragBegins;
    {$else}
    Dragging and Mouse.IsDragging;
    {$endif}
end;

```

I need to add a – maybe – relevant info.
Within my using code I had it - very intentionally -arranged like that, not to have a context menu on an inactive tab (on active tab only);
- don’t want to activate an inactive tab by right click (by left click only)
- don’t want to open a context menu onto an inactive tab.
- don't want to iniitiate a startdrag for an inactive tab (for the active tab only).

So maybe I never recognized the underlying reason for the late changes.
But those are creating the current issue. The left red vertical bar (drag marker) at left click is disturbing.

**Comment by klaus101** [comment]
Just for interest i checked if i could reproduce it with the demo “demo_tabs_as_pagecontrol”. I couldn’t. So I searcned where the difference is to my use case.
I found it in the TATTabs property “DragMode:= dmAutomatic;”.
That one didn’t cause an issue before … but now it does. But it shouldn’t (when simply clicking left mouse button it shouldn't show a drag marker).

**Comment by Alexey-T** [comment]
```
function TATTabs._IsDrag: boolean;
begin

// -- BEFORE 2024/01/23:  This worked for me far better / ... OK
  Result:= Dragging and FMouseDragBegins;

// -- WITH 2024/01/23: probably reason for "Drag marker shown at left click on active tab":
  Result:=
    {$ifdef FPC}
    DragManager.IsDragging; //better check than commented code below: it works when drag was started in another control
    //Dragging and FMouseDragBegins;
    {$else}
    Dragging and Mouse.IsDragging;
    {$endif}
end;
```

do you use FPC? or Delphi?
if you use Delphi try to replace line
```
Dragging and Mouse.IsDragging;
```
with old line
```
Dragging and FMouseDragBegins;
```

**Comment by klaus101** [comment]
Oh sorry ….  Lazarus 3.0 64bit, FPC 3.2.2 on Win 10 x64.
Both    Result:= Dragging and FMouseDragBegins;
or        Result := DragManager.IsDragging and FMouseDragBegins;
will work. But that's just what had been recently changed …

Issue will occur when  “DragMode:= dmAutomatic;” is set (you will see that in the demo too).

**Comment by Alexey-T** [comment]
attabs.pas
```
constructor TATTabs.Create(AOwner: TComponent);
begin
  inherited;

  Caption:= '';
  ControlStyle:= ControlStyle+[csOpaque {$ifdef FPC}, csNoFocus{$endif}];
  DoubleBuffered:= IsDoubleBufferedNeeded;
  DragMode:= dmManual; //required Manual
  ParentColor:= false; //better don't support ParentColor, it's mess in code
  Width:= 400;
  Height:= 35;
                 
```
you see that here code sets Dragmode = dmManual.
it is needed. Manual value.
why do you set Dragmode = dmAutomatic?
try to avoid it, pls.

**Comment by Alexey-T** [comment]
you have
```
// -- WITH 2024/01/23: probably reason for "Drag marker shown at left click on active tab":
  Result:=
    {$ifdef FPC}
    DragManager.IsDragging; //better check than commented code below: it works when drag was started in another control
    //Dragging and FMouseDragBegins;
    {$else}
    Dragging and Mouse.IsDragging;
    {$endif}
```
you have this.
try to add checking of Dragmode = automatic here.
like this
```
    {$ifdef FPC}
    if DragMode = dmAutomatic then
      Result := Dragging and FMouseDragBegins
    else
      Result:= DragManager.IsDragging; //better check than commented code below: it works when drag was started in another control
    //Dragging and FMouseDragBegins;
    {$else}
    Result:=
    Dragging and Mouse.IsDragging;
    {$endif}
```
not tested this yet.

**Comment by klaus101** [comment]
Honestly i don’t quite remember why I’d once set Dragmode to dmAutomatic, and I could simply remove it  (the more you say that dmManual is required).

But as it hadn’t caused a problem yet, and the behavior wouldn’t make a sense at all even when dmAutomatic is set, it’s surely more safe and robust to avoid such explicitely and to apply this additional “if” as you tell (it works of course).

**Comment by Alexey-T** [comment]
i applied the fix, please test it. it is fix which i proposed above.
with demo_tabs and dragmode = automatic, 
it now works.

**Comment by klaus101** [comment]
Works ok for me .. just as expected. Thank you for attention!

**Comment by klaus101** [comment]
So closing ...

**Comment by klaus101** [comment]
Closed
