### ISSUE TITLE
TATListbox: OwnerDrawn + ScrollStyleHorz

### ISSUE THREAD

**Issue by kazuser** [Alexey-T/ATButtons#95]
```
procedure TForm1.FormCreate(Sender: TObject);
begin
  ATListbox1.OwnerDrawn := true;
  ATListbox1.VirtualItemCount := 100;
  ATListbox1.ItemHeight := 25;
  ATListbox1.OnDrawItem := ListboxDraw;
end;

procedure TForm1.ListboxDraw(Sender: TObject; aCanvas: TCanvas; aIndex: integer; const aRect: TRect);
var
  Ls: string;
begin
  Ls := 'Test test test test test test test test test test test test test test test test test test test test test test test test test test ' + aIndex.ToString;

  aCanvas.Brush.Color := clMoneyGreen;
  aCanvas.FillRect(aRect);
  aCanvas.Pen.Color := clMedGray;
  aCanvas.Font.Size := 10;
  aCanvas.TextOut(aRect.Left - ATListbox1.ScrollHorz, (aRect.Top + aRect.Bottom - aCanvas.TextHeight(Ls)) div 2, Ls);
end;
```

`ScrollStyleHorz = alssAuto`:

![alssAuto](https://github.com/Alexey-T/ATFlatControls/assets/3335273/bd177f67-f0f0-48ca-a354-d4a956cd5586)

`ScrollStyleHorz = alssShow`:

![alssShow](https://github.com/Alexey-T/ATFlatControls/assets/3335273/14d252d6-4a9d-451d-bd1c-51a1c41d8c3d)

[Project1.zip](https://github.com/user-attachments/files/15799937/Project1.zip)

**Comment by Alexey-T** [comment]
here listbox control DON'T know real width of content. so it cannot update scrollbar.
you must tell the content width to listbox.
use one of these props (I don't recall which one is needed)

```
    property ColumnSeparator: char read FColumnSep write FColumnSep;
    property ColumnSizes: TATIntArray read FColumnSizes write FColumnSizes;
    property ColumnWidth[AIndex: integer]: integer read GetColumnWidth;
    property OnCalcScrollWidth: TATListboxCalcWidth
```

**Comment by Alexey-T** [comment]
related code in listbox:
```

function TATListbox.GetMaxWidth(C: TCanvas): integer;
var
  i: integer;
begin
  Result:= 0;

  if FVirtualMode then
  begin
    if Assigned(FOnCalcScrollWidth) then
      Result:= FOnCalcScrollWidth(Self, C);
  end
  else
  if ShowColumns then
  begin
    for i:= 0 to High(FColumnWidths) do
      Inc(Result, FColumnWidths[i]);
  end
  else
  begin
    for i:= 0 to Min(ItemCount, Items.Count)-1 do
      Result:= Max(Result, C.TextWidth(Items[i]));
    Inc(Result, FIndentLeft+2);
  end;
end;
```

**Comment by kazuser** [comment]
![image](https://github.com/Alexey-T/ATFlatControls/assets/3335273/90d0044e-f330-4426-bee5-b64c0468ed60)

Replaced `GetMaxWidth` to **public** but it always returns "0", is it ok?

![image](https://github.com/Alexey-T/ATFlatControls/assets/3335273/94c1a93a-885d-4014-871c-0275d4e2a6f1)

**Comment by Alexey-T** [comment]
you did not add event handler, yes?
see the code:
```
  if FVirtualMode then
  begin
    if Assigned(FOnCalcScrollWidth) then
      Result:= FOnCalcScrollWidth(Self, C);
  end
```

it tells that in VirtualMode you must add event handler OnCalcScrollWidth.

**Comment by kazuser** [comment]
I'm sorry, I still can't figure out why the height is calculated automatically, but the width is not :(

Could you help me with this?

**Comment by Alexey-T** [comment]
Because property ItemHeight exists, so listbox can calculate all heights.
listbox cannot calculate width of items in VIRTUAL MODE. to help him, add event handler:

OnCalcScrollWidth
