### ISSUE TITLE
Tabs: after hiding n tabs, cannot click other tabs anymore

### ISSUE THREAD

**Issue by hakwolf** [Alexey-T/ATButtons#96]
I uses TATGroups  add tabs, on DoOnTabClose event,  I write this code

TFmMain.DoOnTabClose
      

      D := (Sender as TATTabs).GetTabData(ATabIndex);
      if D = nil then exit;
      if D.TabObject = nil then exit;

    if   xxxxxx        then
    begin
      D.TabVisible := False;
      lvBfind := False;
      if ATabIndex < PageGroupsMain.PagesCurrent.Tabs.TabCount - 1 then
      begin

        findtab;
        if not lvBfind then
        begin
          if (Sender as TATTabs).GetTabData(ATabIndex + 1).TabVisible = True then
          begin
            curIndex := ATabIndex + 1;
          end
          else
          begin
            curIndex := 0;
          end;
        end;
        lazprint('PageGroupsMain.PagesCurrent.Tabs.TabIndex=' +
          IntToStr(curIndex));
        PageGroupsMain.PagesCurrent.Tabs.TabIndex := curIndex;
      end
      else
      begin
        findtab;
        if not lvBfind then
        begin
          curIndex := 0;
        end;
        lazprint('PageGroupsMain.PagesCurrent.Tabs.TabIndex=' + IntToStr(curIndex));
        PageGroupsMain.PagesCurrent.Tabs.TabIndex := curIndex;
      end;

      ACanClose := False;
      Exit;
    end;   

 I Hope if this tab can't close, hide it or use PageGroupsMain.PagesCurrent.Tabs.HideTab(ATabIndex); instead ,i want use click tree's node to acitve this hide tab to normal . but when have hide tab and some normal tab togerther, in this state , I close some normal tab, but I Find something when normal tab close and between hide tab,that the normal tab  is not acitve, cant's click(exclude tabobject ),and has no close button. 
 otherthing when close all normal tab,the hide tab‘s tabobject's form is show,but i want it is hide,show nothing.

**Comment by Alexey-T** [comment]
Too broken english. Try google translate.

**Comment by hakwolf** [comment]
unit umain;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, Forms, Controls, Graphics, Dialogs, ExtCtrls, ComCtrls,
  ATGroups, uFmTest, attabs;

type

  { TFmMain }

  TFmMain = class(TForm)
    ATGroups1: TATGroups;
    Panel2: TPanel;
    procedure FormCreate(Sender: TObject);
  private
    procedure InitGroups;
    procedure DoOnTabClose(Sender: TObject; ATabIndex: integer;
      var ACanClose, ACanContinue: boolean);
  public

  end;

var
  FmMain: TFmMain;

implementation

{$R *.lfm}

{ TFmMain }

procedure TFmMain.FormCreate(Sender: TObject);
var
  fmTest1, fmTest2, fmtest3, fmTest4: TfmTest;
  NToIndex: integer;
  Data: TATTabData;
begin
  InitGroups;

  fmTest1 := TfmTest.Create(self);
  Data := TATTabData.Create(nil);
  try
    Data.TabObject := fmTest1;
    Data.TabCaption := 'tabone';
    NToIndex := -1;
    NToIndex := ATGroups1.PagesCurrent.AddTab(NToIndex, Data, True);
  finally
    Data.Free;
  end;

  fmTest2 := TfmTest.Create(self);
  fmTest2.Memo1.Text := 'have content test';
  Data := TATTabData.Create(nil);
  try
    Data.TabObject := fmTest2;
    Data.TabCaption := 'tabtwo';
    NToIndex := -1;
    NToIndex := ATGroups1.PagesCurrent.AddTab(NToIndex, Data, True);
  finally
    Data.Free;
  end;

  fmTest3 := TfmTest.Create(self);
  Data := TATTabData.Create(nil);
  try
    Data.TabObject := fmTest3;
    Data.TabCaption := 'tabthree';
    NToIndex := -1;
    NToIndex := ATGroups1.PagesCurrent.AddTab(NToIndex, Data, True);
  finally
    Data.Free;
  end;


  fmTest4 := TfmTest.Create(self);
  Data := TATTabData.Create(nil);
  try
    Data.TabObject := fmTest4;
    Data.TabCaption := 'tabfour';
    NToIndex := -1;
    NToIndex := ATGroups1.PagesCurrent.AddTab(NToIndex, Data, True);
  finally
    Data.Free;
  end;
end;

procedure TFmMain.InitGroups;
begin
  ATGroups1.Align := alClient;
  ATGroups1.Mode := gmOne;
  ATGroups1.OnTabClose := @DoOnTabClose;
  ATGroups1.PagesCurrent.Tabs.OptShowPlusTab := False;
  ATGroups1.PagesCurrent.Tabs.OptVarWidth := True;
  ATGroups1.PagesCurrent.Tabs.OptShowFlat := True;

  ATGroups1.PagesCurrent.Tabs.ColorBg := $00A08080; //$00585858;
  ATGroups1.PagesCurrent.Tabs.ColorTabOver := $00786868; //$00585858;
  ATGroups1.PagesCurrent.Tabs.ColorFont := clWhite;
  ATGroups1.PagesCurrent.Tabs.ColorTabactive := $00C04040; //$00585858;
  ATGroups1.PagesCurrent.Tabs.ColorActiveMark := $00C04040;
end;

procedure TFmMain.DoOnTabClose(Sender: TObject; ATabIndex: integer;
  var ACanClose, ACanContinue: boolean);
var
  D: TATTabData;
begin
  D := (Sender as TATTabs).GetTabData(ATabIndex);
  if D = nil then exit;
  if D.TabObject = nil then exit;

  if D.TabObject is TFmTest then
  begin
    if (Trim((D.TabObject as TFmTest).Memo1.Text) <> '') then
    begin
      ATGroups1.PagesCurrent.Tabs.HideTab(ATabIndex);
      ACanClose := False;
      Exit;
    end;

    D.TabObject.Free;
  end;
end;

end.

object FmMain: TFmMain
  Left = 316
  Height = 643
  Top = 187
  Width = 1007
  Caption = 'FmMain'
  ClientHeight = 643
  ClientWidth = 1007
  OnCreate = FormCreate
  LCLVersion = '3.4.0.0'
  object Panel2: TPanel
    Left = 0
    Height = 643
    Top = 0
    Width = 1007
    Align = alClient
    Caption = 'Panel2'
    ClientHeight = 643
    ClientWidth = 1007
    TabOrder = 0
    object ATGroups1: TATGroups
      Left = 1
      Height = 641
      Top = 1
      Width = 1005
      Align = alClient
      BevelOuter = bvNone
      Caption = 'ATGroups1'
      ClientHeight = 641
      ClientWidth = 1005
      TabOrder = 0
    end
  end
end

unit uFmTest;

{$mode ObjFPC}{$H+}

interface

uses
  Classes, SysUtils, Forms, Controls, Graphics, Dialogs, StdCtrls;

type

  { TFmTest }

  TFmTest = class(TForm)
    Memo1: TMemo;
  private

  public

  end;

var
  FmTest: TFmTest;

implementation

{$R *.lfm}

end.        

object FmTest: TFmTest
  Left = 576
  Height = 492
  Top = 228
  Width = 734
  BorderStyle = bsNone
  Caption = 'FmTest'
  ClientHeight = 492
  ClientWidth = 734
  LCLVersion = '3.4.0.0'
  object Memo1: TMemo
    Left = 0
    Height = 256
    Top = 0
    Width = 734
    Align = alTop
    TabOrder = 0
  end
end


1、Close tabtwo first, then close tabthree. At this point, tabfour won't click anymore.
2、If you continue to close tabone at this time, you can close tabfour. After closing tabfour,you cannot see tabtwo at this time, but you can see fmtest2. If it cannot see tabtwo, can you hide fmtest2.

**Comment by Alexey-T** [comment]
Text in post is not good, attach project in zip.

**Comment by hakwolf** [comment]
[testdemo.zip](https://github.com/user-attachments/files/17448968/testdemo.zip)
1、Close tabtwo first, then close tabthree. At this point, tabfour won't click anymore.
2、If you continue to close tabone at this time, you can close tabfour. After closing tabfour,you cannot see tabtwo at this time, but you can see fmtest2. If it cannot see tabtwo, can you hide fmtest2.

**Comment by Alexey-T** [comment]
Made a change. reworked Tabs.GetTabAt() for hidden tabs. download from git and try again. better?

**Comment by hakwolf** [comment]
The first point has been resolved. Can you solve the second point? When I hide tabtwo, fmtest2 is not hidden. When I want to hide tabtwo, fmtest2 is hidden. When I set  tabtwo.tabvislble=true again, tabtwo displays normally.

**Comment by Alexey-T** [comment]
Can you write steps, what to do, and which step fails? Eg

1. Click x on tabtwo- it must hide tabtwo, all ok
2. Click x on tab3- tab3 dont hide- wrong

**Comment by hakwolf** [comment]
1.Click x on tabtwo- it must hide fmtest2- wrong
2.Click x on all tab- it must  hide fmtest2- wrong

**Comment by Alexey-T** [comment]
demo code
```
  if D.TabObject is TFmTest then
  begin
    if (Trim((D.TabObject as TFmTest).Memo1.Text) <> '') then
    begin
      ATGroups1.PagesCurrent.Tabs.HideTab(ATabIndex);
      ACanClose := False;
      Exit;
    end;

    D.TabObject.Free;
  end;  
```

code does Exit, so it never runs `D.TabObject.Free`. is it bug?

**Comment by Alexey-T** [comment]
Always use triple tick chars for code block, on github.

**Comment by hakwolf** [comment]
When I want to hide tabtwo, hide fmtest2 instead of releasing fmtest. Because later on, when I display tabtwo, I will show fmtest2.

**Comment by Alexey-T** [comment]
As i see your demo does not hide form for tabtwo. So it never hides. Yes?

**Comment by hakwolf** [comment]
yes.

**Comment by Alexey-T** [comment]
So it is demo's bug.

**Comment by hakwolf** [comment]
```
  if D.TabObject is TFmTest then
  begin
    if (Trim((D.TabObject as TFmTest).Memo1.Text) <> '') then
    begin
      ATGroups1.PagesCurrent.Tabs.HideTab(ATabIndex);
      (D.TabObject as Tform).Align := alcustom;
      (D.TabObject as Tform).Hide;    
      ACanClose := False;
      Exit;
    end;

    D.TabObject.Free;
  end;  
```
 it is maybe demo's bug.but use     `  (D.TabObject as Tform).Hide;`   ，But it still can't be well hidden

**Comment by Alexey-T** [comment]
I made a change. test it. seems fixed? ActivateRightTab did not consider hidden tabs.

**Comment by hakwolf** [comment]
[testdemo.zip](https://github.com/user-attachments/files/17450327/testdemo.zip)
If the tab that needs to be hidden is finally closed, then it won't work.

**Comment by Alexey-T** [comment]
Reproduction steps, pls?

**Comment by hakwolf** [comment]
1. Close tabone, tabthree,tabfour-all ok;
2. Close tabtwo-fmtest2 without hiding - wrong.

**Comment by Alexey-T** [comment]
these steps are for __old demo__. i now test on __new demo__ with only tabtwo. steps with new demo?

this new demo don't hide TabObject, so form is not hidden, it's ok.

**Comment by hakwolf** [comment]
[testdemo.zip](https://github.com/user-attachments/files/17450421/testdemo.zip)
tabtwo and tabthree both hidden tab. add code  `(D.TabObject as TForm).hide;`
1、close x on Close tabtwo-ok.
2、close x on Close tabthree-fmtest2 is not hidden- wrong.

**Comment by Alexey-T** [comment]
yes I see

reason: demo calls HideTab which is complex. it sets Data.TabVisible:=false AND ALSO OTHER THINGS
```

function TATTabs.HideTab(AIndex: integer): boolean;
begin
  Result:= IsIndexOk(AIndex);
  if Result then
  begin
    GetTabData(AIndex).TabVisible:= false;
    // if the deleted tab has focus then this needs to shift to the next
    // tab or - if there are none - to the first
    if AIndex=TabIndex then
    begin
      if IsIndexOk(AIndex+1) then
        SetTabIndex(AIndex+1)
      else
        SetTabIndex(0);
    end;
  end;
end;
      
```

can u not call HideTab? only set D.TabVisible:= false?

**Comment by hakwolf** [comment]
I test D.TabVisible:= false instread HideTab is ok.But I feel like HideTab is perfect. HideTab can activate the nearest normal form。

**Comment by Alexey-T** [comment]
I made fix for HideTab. tst it again?

**Comment by hakwolf** [comment]
All tests are normal, thank you very much.
